/* =====================================================================
   COVER LIBRARY — every album on Melodic Mosaic
   ---------------------------------------------------------------------
   Any record in the shop with the same artist + title borrows its cover
   and full release date from here (capitals, "The" and punctuation don't
   matter). Not shown on its own. Add lines in the same shape to give
   more records a cover, or set cover/released in js/inventory.js.
   ===================================================================== */

var MM = "https://b82agbulos.github.io/melodic-mosaic/images/";

window.COVER_LIBRARY = [
  { artist: "Nirvana", album: "Nevermind", released: "1991-09-24", cover: MM + "Nevermind.png" },
  { artist: "Public Enemy", album: "It Takes a Nation of Millions to Hold Us Back", released: "1988-06-28", cover: MM + "It Takes a Nation of Millions to Hold Us Back.jpg" },
  { artist: "The Clash", album: "London Calling", released: "1979-12-14", cover: MM + "London Calling.jpg" },
  { artist: "Sex Pistols", album: "Never Mind the Bollocks, Here's the Sex Pistols", released: "1977-10-28", cover: MM + "Never Mind the Bollocks, Here's the Sex Pistols.png" },
  { artist: "Radiohead", album: "OK Computer", released: "1997-05-21", cover: MM + "Ok Computer.png" },
  { artist: "Television", album: "Marquee Moon", released: "1977-02-08", cover: MM + "Marquee Moon.png" },
  { artist: "The Beatles", album: "Revolver", released: "1966-08-05", cover: MM + "Revolver.png" },
  { artist: "Lauryn Hill", album: "The Miseducation of Lauryn Hill", released: "1998-08-25", cover: MM + "The Miseducation of Lauryn Hill.jpg" },
  { artist: "The Beach Boys", album: "Pet Sounds", released: "1966-05-16", cover: MM + "Pet Sounds.jpg" },
  { artist: "Marvin Gaye", album: "What's Going On", released: "1971-05-21", cover: MM + "What's Going On.jpg" },
  { artist: "David Bowie", album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", released: "1972-06-16", cover: MM + "The Rise And Fall Of Ziggy Stardust And The Spiders From Mars.jpg" },
  { artist: "The Velvet Underground and Nico", album: "The Velvet Underground & Nico", released: "1967-03-12", cover: MM + "The Velvet Underground & Nico.jpg" },
  { artist: "The Smiths", album: "The Queen Is Dead", released: "1986-06-16", cover: MM + "The Queen is Dead.jpg" },
  { artist: "The Rolling Stones", album: "Exile on Main St.", released: "1972-05-12", cover: MM + "Exile On Main St..jpg" },
  { artist: "Joy Division", album: "Closer", released: "1980-07-18", cover: MM + "Closer.jpg" },
  { artist: "Bob Dylan", album: "Highway 61 Revisited", released: "1965-08-30", cover: MM + "Highway 61 Revisited.jpg" },
  { artist: "Bob Dylan", album: "Blonde on Blonde", released: "1966-06-20", cover: MM + "Blonde On Blonde.jpg" },
  { artist: "Massive Attack", album: "Blue Lines", released: "1991-04-08", cover: MM + "Blue Lines.jpg" },
  { artist: "Patti Smith", album: "Horses", released: "1977-11-10", cover: MM + "Horses.jpg" },
  { artist: "Michael Jackson", album: "Thriller", released: "1982-11-29", cover: MM + "Thriller.jpg" },
  { artist: "Nirvana", album: "In Utero", released: "1993-09-21", cover: MM + "In Utero.jpg" },
  { artist: "The Jimi Hendrix Experience", album: "Are You Experienced", released: "1967-05-12", cover: MM + "Are You Experienced.jpg" },
  { artist: "The Beatles", album: "The Beatles", released: "1968-11-22", cover: MM + "The Beatles.png" },
  { artist: "Van Morrison", album: "Astral Weeks", released: "1968-11-29", cover: MM + "Astral Weeks.jpg" },
  { artist: "Prince and the Revolution", album: "Purple Rain", released: "1984-06-25", cover: MM + "Purple Rain.jpg" },
  { artist: "Prince", album: "Sign o' the Times", released: "1987-03-30", cover: MM + "Sign O’ The Times.jpg" },
  { artist: "The Clash", album: "The Clash", released: "1977-04-08", cover: MM + "The Clash.jpg" },
  { artist: "Kendrick Lamar", album: "To Pimp a Butterfly", released: "2015-03-15", cover: MM + "To Pimp a Butterfly.png" },
  { artist: "Portishead", album: "Dummy", released: "1994-08-22", cover: MM + "Dummy.png" },
  { artist: "Joni Mitchell", album: "Blue", released: "1971-06-22", cover: MM + "Blue.jpg" },
  { artist: "My Bloody Valentine", album: "Loveless", released: "1991-11-04", cover: MM + "Loveless.jpg" },
  { artist: "Ramones", album: "Ramones", released: "1976-04-23", cover: MM + "Ramones.jpg" },
  { artist: "Talking Heads", album: "Remain in Light", released: "1980-10-08", cover: MM + "Remain In Light.png" },
  { artist: "Pink Floyd", album: "The Dark Side of the Moon", released: "1973-03-01", cover: MM + "The Dark Side Of The Moon.png" },
  { artist: "The Beatles", album: "Abbey Road", released: "1969-09-26", cover: MM + "Abbey Road.png" },
  { artist: "R.E.M.", album: "Automatic for the People", released: "1992-10-05", cover: MM + "Automatic for the People.jpg" },
  { artist: "The Jimi Hendrix Experience", album: "Electric Ladyland", released: "1968-10-16", cover: MM + "Electric Ladyland.jpg" },
  { artist: "Wu-Tang Clan", album: "Enter the Wu-Tang (36 Chambers)", released: "1993-11-09", cover: MM + "Enter the Wu-Tang (36 Chambers).jpg" },
  { artist: "Tricky", album: "Maxinquaye", released: "1995-02-20", cover: MM + "Maxinquaye.jpg" },
  { artist: "Beck", album: "Odelay", released: "1996-06-18", cover: MM + "Odelay.jpg" },
  { artist: "Dr. Dre", album: "The Chronic", released: "1992-12-15", cover: MM + "The Chronic.jpg" },
  { artist: "Miles Davis", album: "Kind of Blue", released: "1959-08-17", cover: MM + "Kind Of Blue.jpg" },
  { artist: "Joy Division", album: "Unknown Pleasures", released: "1979-06-15", cover: MM + "Unknown Pleasures.jpg" },
  { artist: "Oasis", album: "Definitely Maybe", released: "1994-08-29", cover: MM + "Definitely Maybe.jpg" },
  { artist: "Primal Scream", album: "Screamadelica", released: "1991-09-23", cover: MM + "Screamadelica.jpg" },
  { artist: "Bob Dylan", album: "Blood on the Tracks", released: "1975-01-20", cover: MM + "Blood On The Tracks.jpg" },
  { artist: "U2", album: "The Joshua Tree", released: "1987-03-09", cover: MM + "The Joshua Tree.jpg" },
  { artist: "The Stooges", album: "Fun House", released: "1970-07-07", cover: MM + "Fun House.png" },
  { artist: "Arcade Fire", album: "Funeral", released: "2004-09-14", cover: MM + "Funeral.jpg" },
  { artist: "Nas", album: "Illmatic", released: "1994-04-19", cover: MM + "Illmatic.jpg" },
  { artist: "Nine Inch Nails", album: "The Downward Spiral", released: "1994-03-08", cover: MM + "The Downward Spiral.png" },
  { artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", released: "1967-05-26", cover: MM + "Sgt. Pepper's Lonely Hearts Club Band" },
  { artist: "John Coltrane", album: "A Love Supreme", released: "1965-02-01", cover: MM + "A Love Supreme.jpg" },
  { artist: "Love", album: "Forever Changes", released: "1967-11-01", cover: MM + "Forever Changes.jpg" },
  { artist: "Sonic Youth", album: "Daydream Nation", released: "1988-10-18", cover: MM + "Daydream Nation.jpg" },
  { artist: "The Rolling Stones", album: "Let It Bleed", released: "1969-11-28", cover: MM + "Let It Bleed.jpg" },
  { artist: "The Doors", album: "The Doors", released: "1967-01-04", cover: MM + "The Doors.jpg" },
  { artist: "Led Zeppelin", album: "Untitled aka Led Zeppelin IV", released: "1971-11-08", cover: MM + "Led Zeppelin IV.jpg" },
  { artist: "Led Zeppelin", album: "Led Zeppelin II", released: "1969-10-22", cover: MM + "Led Zeppelin II.jpg" },
  { artist: "Kanye West", album: "My Beautiful Dark Twisted Fantasy", released: "2010-11-22", cover: MM + "My Beautiful Dark Twisted Fantasy.jpg" },
  { artist: "Otis Redding", album: "Otis Blue/Otis Redding Sings Soul", released: "1965-09-15", cover: MM + "Otis Blue-Otis Redding Sings Soul.jpg" },
  { artist: "Blur", album: "Parklife", released: "1994-04-25", cover: MM + "Parklife.png" },
  { artist: "Pulp", album: "Different Class", released: "1995-10-30", cover: MM + "Different Class.jpg" },
  { artist: "Alice in Chains", album: "Dirt", released: "1992-09-29", cover: MM + "Dirt.jpg" },
  { artist: "DJ Shadow", album: "Endtroducing.....", released: "1996-09-16", cover: MM + "Endtroducing......jpg" },
  { artist: "Hole", album: "Live Through This", released: "1994-04-12", cover: MM + "Live Through This.jpg" },
  { artist: "Metallica", album: "Master of Puppets", released: "1986-03-03", cover: MM + "Master of Puppets.png" },
  { artist: "R.E.M.", album: "Murmur", released: "1983-04-12", cover: MM + "Murmur.jpg" },
  { artist: "Beastie Boys", album: "Paul's Boutique", released: "1989-07-25", cover: MM + "Paul's Boutique.jpg" },
  { artist: "Björk", album: "Post", released: "1995-06-07", cover: MM + "Post.png" },
  { artist: "The Notorious B.I.G.", album: "Ready to Die", released: "1994-09-13", cover: MM + "Ready to Die.jpg" },
  { artist: "The Smashing Pumpkins", album: "Siamese Dream", released: "1993-07-27", cover: MM + "Siamese Dream.jpg" },
  { artist: "Jay-Z", album: "The Blueprint", released: "2001-09-11", cover: MM + "The Blueprint.jpg" },
  { artist: "A Tribe Called Quest", album: "The Low End Theory", released: "1991-09-24", cover: MM + "The Low End Theory.png" },
  { artist: "D'Angelo", album: "Voodoo", released: "2000-01-25", cover: MM + "Voodoo.jpg" },
  { artist: "Sly and the Family Stone", album: "There's a Riot Goin' On", released: "1971-11-01", cover: MM + "There's A Riot Goin' On.jpg" },
  { artist: "PJ Harvey", album: "To Bring You My Love", released: "1995-02-27", cover: MM + "To Bring You My Love.jpg" },
  { artist: "Kate Bush", album: "Hounds of Love", released: "1985-09-16", cover: MM + "Hounds Of Love.png" },
  { artist: "The Strokes", album: "Is This It", released: "2001-07-30", cover: MM + "Is This It .jpg" },
  { artist: "Radiohead", album: "Kid A", released: "2000-10-02", cover: MM + "Kid A.png" },
  { artist: "Kraftwerk", album: "Trans-Europe Express", released: "1977-03-01", cover: MM + "Trans-Europe Express.jpg" },
  { artist: "Lou Reed", album: "Transformer", released: "1972-11-08", cover: MM + "Transformer.jpg" },
  { artist: "The Beatles", album: "Rubber Soul", released: "1965-12-03", cover: MM + "Rubber Soul.jpg" },
  { artist: "The Stone Roses", album: "The Stone Roses", released: "1989-05-02", cover: MM + "The Stone Roses.jpg" },
  { artist: "Oasis", album: "(What's the Story) Morning Glory?", released: "1995-10-02", cover: MM + "(What's the Story) Morning Glory-.jpg" },
  { artist: "U2", album: "Achtung Baby", released: "1991-11-18", cover: MM + "Achtung Baby.jpg" },
  { artist: "Outkast", album: "Aquemini", released: "1998-09-29", cover: MM + "Aquemini.jpg" },
  { artist: "D'Angelo", album: "Brown Sugar", released: "1995-07-03", cover: MM + "Brown Sugar.jpg" },
  { artist: "Frank Ocean", album: "Channel Orange", released: "2012-07-10", cover: MM + "Channel Orange.png" },
  { artist: "Beastie Boys", album: "Check Your Head", released: "1992-04-21", cover: MM + "Check Your Head.jpg" },
  { artist: "Black Flag", album: "Damaged", released: "1981-12-05", cover: MM + "Damaged.jpg" },
  { artist: "The Suicide Machines", album: "Destruction by Definition", released: "1996-05-21", cover: MM + "Destruction by Definition.jpg" },
  { artist: "Green Day", album: "Dookie", released: "1994-02-01", cover: MM + "Dookie.jpg" },
  { artist: "David Bowie", album: "Hunky Dory", released: "1971-12-17", cover: MM + "Hunky Dory.jpg" },
  { artist: "Stevie Wonder", album: "Innervisions", released: "1973-08-03", cover: MM + "Innervisions.jpg" },
  { artist: "Fleetwood Mac", album: "Rumours", released: "1977-02-04", cover: MM + "Rumours.jpg" },
  { artist: "Carole King", album: "Tapestry", released: "1971-10-10", cover: MM + "Tapestry.jpg" },
  { artist: "The Band", album: "The Band", released: "1969-09-22", cover: MM + "The Band.png" },
  { artist: "Liz Phair", album: "Exile in Guyville", released: "1993-06-22", cover: MM + "Exile in Guyville.jpg" },
  { artist: "Public Enemy", album: "Fear of a Black Planet", released: "1990-04-10", cover: MM + "Fear Of A Black Planet.jpg" },
  { artist: "Dead Kennedys", album: "Fresh Fruit for Rotting Vegetables", released: "1980-09-02", cover: MM + "Fresh Fruit for Rotting Vegetables.jpg" },
  { artist: "Paul Simon", album: "Graceland", released: "1986-08-25", cover: MM + "Graceland.jpg" },
  { artist: "Massive Attack", album: "Mezzanine", released: "1998-04-20", cover: MM + "Mezzanine.png" },
  { artist: "Black Sabbath", album: "Paranoid", released: "1970-09-18", cover: MM + "Paranoid.png" },
  { artist: "The Stooges", album: "Raw Power", released: "1973-02-07", cover: MM + "Raw Power.jpg" },
  { artist: "Pavement", album: "Slanted and Enchanted", released: "1992-04-20", cover: MM + "Slanted and Enchanted.jpg" },
  { artist: "Stevie Wonder", album: "Songs in the Key of Life", released: "1976-09-28", cover: MM + "Songs in the Key of Life.jpg" },
  { artist: "The Rolling Stones", album: "Sticky Fingers", released: "1971-04-23", cover: MM + "Sticky Fingers.jpg" },
  { artist: "Pearl Jam", album: "Ten", released: "1991-08-27", cover: MM + "Ten.png" },
  { artist: "Radiohead", album: "The Bends", released: "1995-03-13", cover: MM + "The Bends.png" },
  { artist: "James Brown and the Famous Flames", album: "Live at the Apollo", released: "1963-05-01", cover: MM + "Live At The Apollo.jpg" },
  { artist: "Rancid", album: "...And Out Come the Wolves", released: "1995-08-22", cover: MM + "And Out Comes The Wolves.jpg" },
  { artist: "Jane's Addiction", album: "Ritual de lo Habitual", released: "1990-08-21", cover: MM + "Ritual De Lo Habitual.jpg" },
  { artist: "Bruce Springsteen", album: "Born to Run", released: "1975-08-25", cover: MM + "Born To Run.jpg" },
  { artist: "Operation Ivy", album: "Energy", released: "1989-05-28", cover: MM + "Energy.jpg" },
  { artist: "John Lennon", album: "John Lennon/Plastic Ono Band", released: "1970-12-11", cover: MM + "John Lennon-Plastic Ono Band.jpg" },
  { artist: "The Who", album: "Who's Next", released: "1971-08-14", cover: MM + "Who's Next.jpg" },
  { artist: "Pixies", album: "Doolittle", released: "1989-04-17", cover: MM + "Doolittle.jpg" },
  { artist: "De La Soul", album: "3 Feet High and Rising", released: "1989-03-03", cover: MM + "3 Feet High And Rising.jpg" },
  { artist: "Bad Brains", album: "Bad Brains", released: "1982-02-05", cover: MM + "Bad Brains.png" },
  { artist: "Soundgarden", album: "Badmotorfinger", released: "1991-10-08", cover: MM + "Badmotorfinger.png" },
  { artist: "Erykah Badu", album: "Baduizm", released: "1997-02-11", cover: MM + "Baduizm.jpg" },
  { artist: "The Rolling Stones", album: "Beggars Banquet", released: "1968-12-06", cover: MM + "Beggars Banquet.jpg" },
  { artist: "Mos Def", album: "Black on Both Sides", released: "1999-10-12", cover: MM + "Black on Both Sides.jpg" },
  { artist: "Neil Young", album: "After the Gold Rush", released: "1970-09-19", cover: MM + "After The Gold Rush.jpg" },
  { artist: "Black Sabbath", album: "Black Sabbath", released: "1970-02-13", cover: MM + "Black Sabbath.png" },
  { artist: "Pavement", album: "Crooked Rain, Crooked Rain", released: "1994-02-14", cover: MM + "Crooked Rain, Crooked Rain.jpg" },
  { artist: "Sleater-Kinney", album: "Dig Me Out", released: "1991-04-08", cover: MM + "Dig Me Out.jpg" },
  { artist: "The Chemical Brothers", album: "Dig Your Own Hole", released: "1997-04-07", cover: MM + "Dig Your Own Hole.jpg" },
  { artist: "Cream", album: "Disraeli Gears", released: "1967-11-02", cover: MM + "Disraeli Gears.jpg" },
  { artist: "Suede", album: "Dog Man Star", released: "1994-10-10", cover: MM + "Dog Man Star.jpg" },
  { artist: "Snoop Doggy Dogg", album: "Doggystyle", released: "1993-11-23", cover: MM + "Doggystyle.jpg" },
  { artist: "The White Stripes", album: "Elephant", released: "2003-04-01", cover: MM + "Elephant.jpg" },
  { artist: "Discharge", album: "Hear Nothing See Nothing Say Nothing", released: "1982-05-21", cover: MM + "Hear Nothing See Nothing Say Nothing.jpg" },
  { artist: "Less Than Jake", album: "Hello Rockview", released: "1998-10-06", cover: MM + "Hello Rockview.jpg" },
  { artist: "Miles Davis", album: "In a Silent Way", released: "1969-07-30", cover: MM + "In A Silent Way.jpg" },
  { artist: "Neutral Milk Hotel", album: "In the Aeroplane Over the Sea", released: "1998-02-10", cover: MM + "In the Aeroplane Over the Sea.jpg" },
  { artist: "The Damned", album: "Machine Gun Etiquette", released: "1979-11-02", cover: MM + "Machine Gun Etiquette.jpg" },
  { artist: "Madvillain", album: "Madvillainy", released: "2004-03-23", cover: MM + "Madvillainy.png" },
  { artist: "Led Zeppelin", album: "Physical Graffiti", released: "1975-02-24", cover: MM + "Physical Graffiti.jpg" },
  { artist: "Rage Against the Machine", album: "Rage Against the Machine", released: "1992-11-03", cover: MM + "Rage Against The Machine.png" },
  { artist: "Slayer", album: "Reign in Blood", released: "1986-10-07", cover: MM + "Reign in Blood.jpg" },
  { artist: "Napalm Death", album: "Scum", released: "1987-07-01", cover: MM + "Scum.png" },
  { artist: "N.W.A", album: "Straight Outta Compton", released: "1988-08-08", cover: MM + "Straight Outta Compton.jpg" },
  { artist: "Deafheaven", album: "Sunbather", released: "2013-06-11", cover: MM + "Sunbather.jpg" },
  { artist: "Jeff Buckley", album: "Grace", released: "1994-08-23", cover: MM + "Grace.jpg" },
  { artist: "Eminem", album: "The Marshall Mathers LP", released: "2000-05-23", cover: MM + "The Marshall Mathers LP.png" },
  { artist: "Iron Maiden", album: "The Number of the Beast", released: "1982-03-22", cover: MM + "The Number of the Beast.jpg" },
  { artist: "The Descendents", album: "Milo Goes to College", released: "1982-09-04", cover: MM + "Milo Goes To College.jpg" },
  { artist: "Depeche Mode", album: "Violator", released: "1990-03-19", cover: MM + "Violator.png" },
  { artist: "Pearl Jam", album: "Vs.", released: "1993-10-19", cover: MM + "Vs..jpg" },
  { artist: "Wilco", album: "Yankee Hotel Foxtrot", released: "2001-09-18", cover: MM + "Yankee Hotel Foxtrot.jpg" },
  { artist: "David Bowie", album: "Low", released: "1977-01-14", cover: MM + "Low.jpg" },
  { artist: "Bob Dylan", album: "Bringing It All Back Home", released: "1965-03-25", cover: MM + "Bringing It All Back Home.jpg" },
  { artist: "Catch 22", album: "Keasbey Nights", released: "1998-03-24", cover: MM + "Keasbey Nights.jpg" },
  { artist: "Led Zeppelin", album: "Led Zeppelin", released: "1969-01-12", cover: MM + "Led Zeppelin.jpg" },
  { artist: "The Band", album: "Music from Big Pink", released: "1968-07-01", cover: MM + "Music From Big Pink.jpg" },
  { artist: "Elvis Presley", album: "The Sun Sessions", released: "1976-03-21", cover: MM + "The Sun Sessions.jpg" },
  { artist: "Captain Beefheart and his Magic Band", album: "Trout Mask Replica", released: "1969-06-16", cover: MM + "Trout Mask Replica.png" },
  { artist: "Queen", album: "A Night at the Opera", released: "1975-11-21", cover: MM + "A Night at the Opera.png" },
  { artist: "Tool", album: "Ænima", released: "1996-09-17", cover: MM + "AEima.jpg" },
  { artist: "Sigur Rós", album: "Ágætis byrjun", released: "1999-06-12", cover: MM + "Ágætis Byrjun.jpg" },
  { artist: "Ice Cube", album: "AmeriKKKa's Most Wanted", released: "1990-05-16", cover: MM + "AmeriKKKa's Most Wanted.jpg" },
  { artist: "Metallica", album: "...And Justice for All", released: "1988-09-07", cover: MM + "And Justice For All.jpg" },
  { artist: "Guns N' Roses", album: "Appetite for Destruction", released: "1987-07-21", cover: MM + "Appetite for Destruction.png" },
  { artist: "Danny Brown", album: "Atrocity Exhibition", released: "2016-09-27", cover: MM + "Atrocity Exhibition.jpg" },
  { artist: "Amy Winehouse", album: "Back to Black", released: "2006-10-27", cover: MM + "Back To Black.jpg" },
  { artist: "Miles Davis", album: "Bitches Brew", released: "1970-03-30", cover: MM + "Bitches Brew.jpg" },
  { artist: "David Bowie", album: "Blackstar", released: "2016-01-08", cover: MM + "Blackstar.png" },
  { artist: "Opeth", album: "Blackwater Park", released: "2001-03-12", cover: MM + "Blackwater Park.jpg" },
  { artist: "Ozzy Osbourne", album: "Blizzard of Ozz", released: "1980-09-12", cover: MM + "Blizzard of Ozz.png" },
  { artist: "Bruce Springsteen", album: "Born in the U.S.A.", released: "1984-06-04", cover: MM + "Born in the U.S.A..jpg" },
  { artist: "Judas Priest", album: "British Steel", released: "1980-04-14", cover: MM + "British Steel.jpg" },
  { artist: "Sepultura", album: "Chaos A.D.", released: "1993-09-01", cover: MM + "Chaos A.D..jpg" },
  { artist: "Janet Jackson", album: "Control", released: "1986-02-04", cover: MM + "Control.jpg" },
  { artist: "Pet Shop Boys", album: "Actually", released: "1987-09-07", cover: MM + "Actually.jpg" },
  { artist: "Sugar", album: "Copper Blue", released: "1992-09-04", cover: MM + "Copper Blue.jpg" },
  { artist: "TLC", album: "CrazySexyCool", released: "1994-11-15", cover: MM + "CrazySexyCool.png" },
  { artist: "The Slits", album: "Cut", released: "1979-09-07", cover: MM + "Cut.jpg" },
  { artist: "Björk", album: "Debut", released: "1993-07-05", cover: MM + "Debut.jpg" },
  { artist: "Minutemen", album: "Double Nickels on the Dime", released: "1984-07-03", cover: MM + "Double Nickels on the Dime.jpg" },
  { artist: "Gang of Four", album: "Entertainment!", released: "1979-09-25", cover: MM + "Entertainment!.jpg" },
  { artist: "The Sisters of Mercy", album: "Floodland", released: "1987-11-16", cover: MM + "Floodland.jpg" },
  { artist: "Front 242", album: "Front by Front", released: "1988-11-01", cover: MM + "Front By Front.png" },
  { artist: "Sonic Youth", album: "Goo", released: "1990-06-26", cover: MM + "Goo.png" },
  { artist: "Kendrick Lamar", album: "Good Kid, M.A.A.D City", released: "2012-10-22", cover: MM + "Good Kid, M.A.A.D City.jpg" },
  { artist: "Carcass", album: "Heartwork", released: "1993-10-18", cover: MM + "Heartwork.jpg" },
  { artist: "Björk", album: "Homogenic", released: "1997-09-20", cover: MM + "Homogenic.jpg" },
  { artist: "Sinéad O'Connor", album: "I Do Not Want What I Haven't Got", released: "1990-03-20", cover: MM + "I Do Not Want What I Haven't Got.jpg" },
  { artist: "The Beat", album: "I Just Can't Stop It", released: "1980-05-23", cover: MM + "I Just Can’t Stop It.jpg" },
  { artist: "Aretha Franklin", album: "I Never Loved a Man the Way I Love You", released: "1967-03-10", cover: MM + "I Never Loved a Man the Way I Love You.png" },
  { artist: "Beastie Boys", album: "Ill Communication", released: "1994-05-31", cover: MM + "Ill Communication.jpg" },
  { artist: "Sufjan Stevens", album: "Illinois", released: "2005-07-04", cover: MM + "Illinois.jpg" },
  { artist: "John Lennon", album: "Imagine", released: "1971-09-09", cover: MM + "Imagine.jpg" },
  { artist: "Elvis Costello and the Attractions", album: "Imperial Bedroom", released: "1982-07-02", cover: MM + "Imperial Bedroom.jpg" },
  { artist: "Radiohead", album: "In Rainbows", released: "2007-10-10", cover: MM + "In Rainbows.png" },
  { artist: "Bauhaus", album: "In the Flat Field", released: "1980-11-03", cover: MM + "In the Flat Field.jpg" },
  { artist: "Wes Montgomery", album: "The Incredible Jazz Guitar of Wes Montgomery", released: "1960-04-01", cover: MM + "Incredible Jazz Guitar.jpg" },
  { artist: "Converge", album: "Jane Doe", released: "2001-09-04", cover: MM + "Jane Doe.jpg" },
  { artist: "M.I.A.", album: "Kala", released: "2007-08-08", cover: MM + "Kala.jpg" },
  { artist: "Killing Joke", album: "Killing Joke", released: "1980-10-05", cover: MM + "Killing Joke.jpg" },
  { artist: "Robert Johnson", album: "King of the Delta Blues Singers", released: "1961-01-01", cover: MM + "King Of The Delta Blues Singers.jpg" },
  { artist: "The Breeders", album: "Last Splash", released: "1993-08-30", cover: MM + "Last Splash.jpg" },
  { artist: "Derek and the Dominos", album: "Layla and Other Assorted Love Songs", released: "1970-11-26", cover: MM + "Layla and Other Assorted Love Songs.jpg" },
  { artist: "Beyoncé", album: "Lemonade", released: "2016-04-23", cover: MM + "Lemonade.png" },
  { artist: "Beyoncé", album: "Beyoncé", released: "2013-12-13", cover: MM + "Beyoncé.png" },
  { artist: "PJ Harvey", album: "Let England Shake", released: "2011-02-14", cover: MM + "Let England Shake.jpg" },
  { artist: "The Mighty Mighty Bosstones", album: "Let's Face It", released: "1997-03-11", cover: MM + "Let's Face It.jpg" },
  { artist: "Mastodon", album: "Leviathan", released: "2004-08-31", cover: MM + "Leviathan.jpg" },
  { artist: "Big Daddy Kane", album: "Long Live the Kane", released: "1988-06-21", cover: MM + "Long Live the Kane.jpg" },
  { artist: "LL Cool J", album: "Mama Said Knock You Out", released: "1990-09-14", cover: MM + "Mama Said Knock You Out.jpg" },
  { artist: "Black Sabbath", album: "Master of Reality", released: "1971-07-21", cover: MM + "Master of Reality.png" },
  { artist: "Animal Collective", album: "Merriweather Post Pavilion", released: "2009-01-06", cover: MM + "Merriweather Post Pavilion.png" },
  { artist: "Vampire Weekend", album: "Modern Vampires of the City", released: "2013-05-14", cover: MM + "Modern Vampires of the City.jpg" },
  { artist: "Air", album: "Moon Safari", released: "1998-01-16", cover: MM + "Moon Safari.jpg" },
  { artist: "Black Star", album: "Mos Def & Talib Kweli Are Black Star", released: "1998-09-29", cover: MM + "Mos Def & Talib Kweli Are Black Star.jpg" },
  { artist: "Elvis Costello", album: "My Aim Is True", released: "1977-07-22", cover: MM + "My Aim Is True.jpg" },
  { artist: "Raekwon", album: "Only Built 4 Cuban Linx...", released: "1995-08-01", cover: MM + "Only Built 4 Cuban Linx….jpg" },
  { artist: "R.E.M.", album: "Out of Time", released: "1991-03-12", cover: MM + "Out Of Time.jpg" },
  { artist: "Eric B. & Rakim", album: "Paid in Full", released: "1987-07-07", cover: MM + "Paid in Full.jpg" },
  { artist: "Megadeth", album: "Peace Sells... but Who's Buying?", released: "1986-09-19", cover: MM + "Peace Sells... But Who's Buying-.jpg" },
  { artist: "The Cure", album: "Disintegration", released: "1989-05-02", cover: MM + "Disintegration.jpg" },
  { artist: "The Cure", album: "Pornography", released: "1982-05-03", cover: MM + "Pornography.png" },
  { artist: "Portishead", album: "Portishead", released: "1997-09-16", cover: MM + "Portishead.png" },
  { artist: "The Jesus and Mary Chain", album: "Psychocandy", released: "1985-11-18", cover: MM + "Psychocandy.png" },
  { artist: "Unkle", album: "Psyence Fiction", released: "1998-08-24", cover: MM + "Psyence Fiction.png" },
  { artist: "Jay-Z", album: "Reasonable Doubt", released: "1996-06-25", cover: MM + "Reasonable Doubt.jpg" },
  { artist: "Fugazi", album: "Repeater", released: "1990-04-19", cover: MM + "Repeater.jpg" },
  { artist: "Megadeth", album: "Rust in Peace", released: "1990-09-24", cover: MM + "Rust In Peace.jpg" },
  { artist: "Buzzcocks", album: "Singles Going Steady", released: "1979-09-25", cover: MM + "Singles Going Steady.jpg" },
  { artist: "At the Gates", album: "Slaughter of the Soul", released: "1995-11-14", cover: MM + "Slaughter of the Soul.png" },
  { artist: "LCD Soundsystem", album: "Sound of Silver", released: "2007-03-12", cover: MM + "Sound Of Silver.jpg" },
  { artist: "Suicidal Tendencies", album: "Suicidal Tendencies", released: "1983-07-05", cover: MM + "Suicidal Tendencies.jpg" },
  { artist: "Soundgarden", album: "Superunknown", released: "1994-03-08", cover: MM + "Superunknown.png" },
  { artist: "Siouxsie and the Banshees", album: "Juju", released: "1981-06-19", cover: MM + "Juju.jpg" },
  { artist: "Nick Cave and the Bad Seeds", album: "Tender Prey", released: "1988-09-19", cover: MM + "Tender Prey.jpg" },
  { artist: "Pixies", album: "Surfer Rosa", released: "1988-03-21", cover: MM + "Surfer Rosa.jpg" },
  { artist: "Drake", album: "Take Care", released: "2011-11-15", cover: MM + "Take Care.jpg" },
  { artist: "Charles Mingus", album: "The Black Saint and the Sinner Lady", released: "1963-07-01", cover: MM + "The Black Saint and Sinner Lady.jpg" },
  { artist: "Fiona Apple", album: "The Idler Wheel Is Wiser Than the Driver of the Screw and Whipping Cords Will Serve You More Than Ropes Will Ever Do", released: "2012-06-18", cover: MM + "The Idler Wheel Is Wiser Than the Driver of the Screw and Whipping Cords Will Serve You More Than Ropes Will Ever Do.png" },
  { artist: "The Inner Mounting Flame", album: "The Inner Mounting Flame", released: "1971-08-14", cover: MM + "The Inner Mounting Flame.jpg" },
  { artist: "Ministry", album: "The Land of Rape and Honey", released: "1988-10-11", cover: MM + "The Land Of Rape And Honey.jpg" },
  { artist: "Modest Mouse", album: "The Moon & Antarctica", released: "2000-06-13", cover: MM + "The Moon & Antarctica.png" },
  { artist: "Dance Hall Crashers", album: "The Old Record (1989-1992)", released: "1996-11-19", cover: MM + "The Old Record.jpg" },
  { artist: "Refused", album: "The Shape of Punk to Come", released: "1998-10-27", cover: MM + "The Shape of Punk to Come.jpg" },
  { artist: "The Flaming Lips", album: "The Soft Bulletin", released: "1999-05-17", cover: MM + "The Soft Bulletin.jpg" },
  { artist: "X", album: "Los Angeles", released: "1980-04-26", cover: MM + "Los Angeles.jpg" },
  { artist: "The Specials", album: "The Specials", released: "1979-10-19", cover: MM + "The Specials.jpg" },
  { artist: "The Velvet Underground", album: "The Velvet Underground", released: "1969-03-01", cover: MM + "The Velvet Underground.jpg" },
  { artist: "LCD Soundsystem", album: "This Is Happening", released: "2010-05-17", cover: MM + "This Is Happening.jpg" },
  { artist: "Neurosis", album: "Through Silver in Blood", released: "1996-04-02", cover: MM + "Through Silver In Blood.jpg" },
  { artist: "System of a Down", album: "Toxicity", released: "2001-09-04", cover: MM + "Toxicity.png" },
  { artist: "No Doubt", album: "Tragic Kingdom", released: "1995-10-10", cover: MM + "Tragic Kingdom.jpg" },
  { artist: "Misfits", album: "Walk Among Us", released: "1982-03-01", cover: MM + "Walk Among Us.jpg" },
  { artist: "Arctic Monkeys", album: "Whatever People Say I Am, That's What I'm Not", released: "2006-01-23", cover: MM + "Whatever People Say I Am, That’s What I’m Not.jpg" },
  { artist: "Kanye West", album: "Yeezus", released: "2013-06-18", cover: MM + "Yeezus.jpg" },
  { artist: "Arrested Development", album: "3 Years, 5 Months and 2 Days in the Life Of...", released: "1992-03-24", cover: MM + "3 Years, 5 Months, And 2 Days In The Life Of....png" },
  { artist: "Metallica", album: "Ride the Lightning", released: "1984-07-27", cover: MM + "Ride the Lightning.png" },
  { artist: "The Streets", album: "A Grand Don't Come for Free", released: "2004-05-17", cover: MM + "A Grand Don’t Come for Free.jpg" },
  { artist: "AC/DC", album: "Back in Black", released: "1980-07-25", cover: MM + "Back in Black.jpg" },
  { artist: "Frank Ocean", album: "Blonde", released: "2016-08-20", cover: MM + "Blonde.png" },
  { artist: "Daft Punk", album: "Discovery", released: "2001-03-12", cover: MM + "Discovery.png" },
  { artist: "Electric Wizard", album: "Dopethrone", released: "2000-09-25", cover: MM + "Dopethrone.jpg" },
  { artist: "Elastica", album: "Elastica", released: "1995-03-13", cover: MM + "Elastica.jpg" },
  { artist: "Marvin Gaye", album: "Let's Get It On", released: "1973-08-28", cover: MM + "Let's Get it On.png" },
  { artist: "Michael Jackson", album: "Off the Wall", released: "1979-08-10", cover: MM + "Off the Wall.jpg" },
  { artist: "Bob Dylan", album: "Time Out of Mind", released: "1997-09-30", cover: MM + "Time Out Of Mind.jpg" },
  { artist: "Lorde", album: "Melodrama", released: "2017-06-16", cover: MM + "Melodrama.jpg" },
  { artist: "Outkast", album: "Stankonia", released: "2000-10-31", cover: MM + "Stankonia.png" },
  { artist: "Swans", album: "To Be Kind", released: "2014-05-12", cover: MM + "To Be Kind.png" },
  { artist: "Burial", album: "Untrue", released: "2007-11-05", cover: MM + "Untrue.jpg" },
  { artist: "Death Grips", album: "The Money Store", released: "2012-04-24", cover: MM + "The Money Store.jpg" },
  { artist: "Neil Young & Crazy Horse", album: "Ragged Glory", released: "1990-09-09", cover: MM + "Ragged Glory.jpg" },
  { artist: "Grizzly Bear", album: "Veckatimest", released: "2009-05-26", cover: MM + "Veckatimest.jpg" },
  { artist: "Interpol", album: "Turn On the Bright Lights", released: "2002-08-19", cover: MM + "Turn On The Bright Lights.png" },
  { artist: "LCD Soundsystem", album: "LCD Soundsystem", released: "2005-01-24", cover: MM + "LCD Soundsytem.jpg" },
  { artist: "Portishead", album: "Third", released: "2008-04-28", cover: MM + "Third.png" },
  { artist: "Fugees", album: "The Score", released: "1996-02-13", cover: MM + "The Score.jpg" },
  { artist: "Kanye West", album: "Late Registration", released: "2005-08-30", cover: MM + "Late Registration.png" },
  { artist: "Run the Jewels", album: "Run the Jewels 2", released: "2014-10-24", cover: MM + "Run the Jewels 2.jpg" },
  { artist: "The Smashing Pumpkins", album: "Mellon Collie and the Infinite Sadness", released: "1995-10-24", cover: MM + "Mellon Collie and the Infinite Sadness.jpg" },
  { artist: "PJ Harvey", album: "Rid of Me", released: "1993-05-04", cover: MM + "Rid Of Me.jpg" },
  { artist: "Funkadelic", album: "Maggot Brain", released: "1971-07-12", cover: MM + "Maggot Brain.jpg" },
  { artist: "Alanis Morissette", album: "Jagged Little Pill", released: "1995-06-13", cover: MM + "Jagged little pill.jpg" },
  { artist: "Charles Mingus", album: "Mingus Ah Um", released: "1959-10-01", cover: MM + "Mingus Ah Um.jpg" },
  { artist: "Sonny Rollins", album: "Saxophone Colossus", released: "1957-03-31", cover: MM + "Saxophone Colossus.jpg" },
  { artist: "The Dave Brubeck Quartet", album: "Time Out", released: "1959-12-14", cover: MM + "Time Out.jpg" },
  { artist: "Cannonball Adderley", album: "Somethin' Else", released: "1958-08-01", cover: MM + "Somethin' Else.jpg" },
  { artist: "John Coltrane", album: "Giant Steps", released: "1960-02-01", cover: MM + "Giant Steps.jpg" },
  { artist: "Herbie Hancock", album: "Maiden Voyage", released: "1965-03-18", cover: MM + "Maiden Voyage.jpg" },
  { artist: "Art Blakey and the Jazz Messengers", album: "Moanin'", released: "1959-01-01", cover: MM + "Moanin'.jpg" },
  { artist: "Eric Dolphy", album: "Out to Lunch!", released: "1964-08-01", cover: MM + "Out to Lunch!.png" },
  { artist: "Keith Jarrett", album: "The Köln Concert", released: "1975-11-30", cover: MM + "The Köln Concert.jpg" },
  { artist: "Stan Getz and João Gilberto", album: "Getz/Gilberto", released: "1964-03-01", cover: MM + "Getz-Gilberto.jpg" },
  { artist: "Ornette Coleman", album: "The Shape of Jazz to Come", released: "1959-11-01", cover: MM + "The Shape of Jazz to Come.jpg" },
  { artist: "Duke Ellington", album: "Ellington at Newport", released: "1956-11-01", cover: MM + "Ellington At Newport.jpg" },
  { artist: "Herbie Hancock", album: "Head Hunters", released: "1973-10-26", cover: MM + "Head Hunters.jpg" },
  { artist: "The Horace Silver Quintet", album: "Song for My Father", released: "1965-01-31", cover: MM + "Song for My Father.jpg" },
  { artist: "Miles Davis", album: "Birth of the Cool", released: "1957-02-01", cover: MM + "Birth of the Cool.jpg" },
  { artist: "Mobb Deep", album: "The Infamous", released: "1995-04-25", cover: MM + "The Infamous.jpg" },
  { artist: "Ghostface Killah", album: "Supreme Clientele", released: "2000-02-08", cover: MM + "Supreme Clientele.jpg" },
  { artist: "Clipse", album: "Hell Hath No Fury", released: "2006-11-28", cover: MM + "Hell Hath No Fury.jpg" },
  { artist: "The Notorious B.I.G.", album: "Life After Death", released: "1997-03-25", cover: MM + "Life After Death.jpg" },
  { artist: "EPMD", album: "Strictly Business", released: "1988-06-07", cover: MM + "Strictly Business.jpg" },
  { artist: "GZA", album: "Liquid Swords", released: "1995-11-07", cover: MM + "Liquid Swords.jpeg" },
  { artist: "Ministry", album: "ΚΕΦΑΛΗΞΘ aka Psalm 69: The Way to Succeed and the Way to Suck Eggs", released: "1992-07-14", cover: MM + "Psalm 69- The Way To Succeed And The Way To Suck Eggs.jpg" },
  { artist: "Nine Inch Nails", album: "Broken", released: "1992-09-22", cover: MM + "Broken.png" },
  { artist: "KMFDM", album: "Nihil", released: "1995-04-04", cover: MM + "Nihil.jpg" },
  { artist: "X-Ray Spex", album: "Germfree Adolescents", released: "1978-11-10", cover: MM + "Germfree Adolescents.jpg" },
  { artist: "Wire", album: "Pink Flag", released: "1977-12-01", cover: MM + "Pink Flag.jpg" },
  { artist: "Hüsker Dü", album: "Zen Arcade", released: "1984-07-01", cover: MM + "Zen Arcade.jpg" },
  { artist: "New York Dolls", album: "New York Dolls", released: "1973-07-27", cover: MM + "New York Dolls.png" },
  { artist: "Minor Threat", album: "Complete Discography", released: "1989-01-01", cover: MM + "Complete Discography.jpg" },
  { artist: "Mission of Burma", album: "Vs.", released: "1982-10-11", cover: MM + "Vs..jpeg" },
  { artist: "The Raincoats", album: "The Raincoats", released: "1979-11-21", cover: MM + "The Raincoats.jpg" },
  { artist: "Ramones", album: "Rocket to Russia", released: "1977-11-04", cover: MM + "Rocket To Russia.jpg" },
  { artist: "The Velvet Underground", album: "White Light/White Heat", released: "1968-01-30", cover: MM + "White Light-White Heat.jpg" },
  { artist: "Richard Hell & the Voidoids", album: "Blank Generation", released: "1977-09-01", cover: MM + "Blank Generation.jpg" },
  { artist: "Yeah Yeah Yeahs", album: "Fever to Tell", released: "2003-04-29", cover: MM + "Fever To Tell.jpg" }
];
