/* =====================================================================
   STARTER STOCK — demo shelves borrowed from Melodic Mosaic
   ---------------------------------------------------------------------
   Only shown while sheetFeed in js/shop-map.js is empty, so the rooms
   aren't bare before the spreadsheet is connected. Safe to delete after.
   ===================================================================== */

var MM = "https://b82agbulos.github.io/melodic-mosaic/images/";

window.STARTER_STOCK = [
  { artist: "Nirvana",
    album: "Nevermind",
    released: "1991-09-24",
    sections: ["grunge"],
    cover: MM + "Nevermind.png",
    link: "",
    spotify: "spotify:album:2guirTSEqLizK7j9i1MTTZ" },
  { artist: "Nirvana",
    album: "In Utero",
    released: "1993-09-21",
    sections: ["grunge"],
    cover: MM + "In Utero.jpg",
    link: "",
    spotify: "spotify:album:7wOOA7l306K8HfBKfPoafr" },
  { artist: "Pearl Jam",
    album: "Ten",
    released: "1991-08-27",
    sections: ["grunge"],
    cover: MM + "Ten.png",
    link: "",
    spotify: "spotify:album:5B4PYA7wNN4WdEXdIJu58a" },
  { artist: "Pearl Jam",
    album: "Vs.",
    released: "1993-10-19",
    sections: ["grunge"],
    cover: MM + "Vs..jpg",
    link: "",
    spotify: "spotify:album:3BSOiAas8BpJOii3kCPyjV" },
  { artist: "Soundgarden",
    album: "Badmotorfinger",
    released: "1991-10-08",
    sections: ["grunge"],
    cover: MM + "Badmotorfinger.png",
    link: "",
    spotify: "spotify:album:2W6MaUiInBkna5DfBES4E3" },
  { artist: "Soundgarden",
    album: "Superunknown",
    released: "1994-03-08",
    sections: ["grunge"],
    cover: MM + "Superunknown.png",
    link: "",
    spotify: "spotify:album:4K8bxkPDa5HENw0TK7WxJh" },
  { artist: "Alice in Chains",
    album: "Dirt",
    released: "1992-09-29",
    sections: ["grunge"],
    cover: MM + "Dirt.jpg",
    link: "",
    spotify: "spotify:album:58NXIEYqmq5dQHg9nV9duM" },
  { artist: "Hole",
    album: "Live Through This",
    released: "1994-04-12",
    sections: ["grunge"],
    cover: MM + "Live Through This.jpg",
    link: "",
    spotify: "spotify:album:2Rwf2nPYZQ9aIe4QXACTC7" },
  { artist: "The Smashing Pumpkins",
    album: "Siamese Dream",
    released: "1993-07-27",
    sections: ["grunge"],
    cover: MM + "Siamese Dream.jpg",
    link: "",
    spotify: "spotify:album:0bQglEvsHphrS19FGODEGo" },
  { artist: "Pixies",
    album: "Surfer Rosa",
    released: "1988-03-21",
    sections: ["indie-alt"],
    cover: MM + "Surfer Rosa.jpg",
    link: "",
    spotify: "spotify:album:50j4Wm1b9hLpSpPIA39Vp9" },
  { artist: "Pixies",
    album: "Doolittle",
    released: "1989-04-17",
    sections: ["indie-alt"],
    cover: MM + "Doolittle.jpg",
    link: "",
    spotify: "spotify:album:0DQyTVcDhK9wm0f6RaErWO" },
  { artist: "Pavement",
    album: "Slanted and Enchanted",
    released: "1992-04-20",
    sections: ["indie-alt"],
    cover: MM + "Slanted and Enchanted.jpg",
    link: "",
    spotify: "spotify:album:7o14zVcXSRk7clV6QCEdOD" },
  { artist: "Pavement",
    album: "Crooked Rain, Crooked Rain",
    released: "1994-02-14",
    sections: ["indie-alt"],
    cover: MM + "Crooked Rain, Crooked Rain.jpg",
    link: "",
    spotify: "spotify:album:1XFNz6KIvLyIsLFOiLRKqP" },
  { artist: "The Strokes",
    album: "Is This It",
    released: "2001-07-30",
    sections: ["indie-alt"],
    cover: MM + "Is This It .jpg",
    link: "",
    spotify: "spotify:album:2k8KgmDp9oHrmu0MIj4XDE" },
  { artist: "Neutral Milk Hotel",
    album: "In the Aeroplane Over the Sea",
    released: "1998-02-10",
    sections: ["indie-alt"],
    cover: MM + "In the Aeroplane Over the Sea.jpg",
    link: "",
    spotify: "spotify:album:0vVekV45lOaVKs6RZQQNob" },
  { artist: "Modest Mouse",
    album: "The Moon & Antarctica",
    released: "2000-06-13",
    sections: ["indie-alt"],
    cover: MM + "The Moon & Antarctica.png",
    link: "",
    spotify: "spotify:album:5SbcupirEParczvqqyUPXL" },
  { artist: "Radiohead",
    album: "The Bends",
    released: "1995-03-13",
    sections: ["indie-alt"],
    cover: MM + "The Bends.png",
    link: "",
    spotify: "spotify:album:35UJLpClj5EDrhpNIi4DFg" },
  { artist: "Radiohead",
    album: "OK Computer",
    released: "1997-05-21",
    sections: ["indie-alt"],
    cover: MM + "Ok Computer.png",
    link: "",
    spotify: "spotify:album:6dVIqQ8qmQ5GBnJ9shOYGE" },
  { artist: "The Breeders",
    album: "Last Splash",
    released: "1993-08-30",
    sections: ["indie-alt"],
    cover: MM + "Last Splash.jpg",
    link: "",
    spotify: "spotify:album:57F44c0MTziVzHPEuJtH9A" },
  { artist: "Sonic Youth",
    album: "Daydream Nation",
    released: "1988-10-18",
    sections: ["experimental-rock"],
    cover: MM + "Daydream Nation.jpg",
    link: "",
    spotify: "spotify:album:3BYlBcND6PeKoW6ZODjZO3" },
  { artist: "Swans",
    album: "To Be Kind",
    released: "2014-05-12",
    sections: ["experimental-rock"],
    cover: MM + "To Be Kind.png",
    link: "",
    spotify: "spotify:album:4dq7JNcHKrnozzFQg5bpmn" },
  { artist: "Sigur Rós",
    album: "Ágætis byrjun",
    released: "1999-06-12",
    sections: ["experimental-rock"],
    cover: MM + "Ágætis Byrjun.jpg",
    link: "",
    spotify: "spotify:album:1DMMv1Kmoli3Y9fVEZDUVC" },
  { artist: "The Velvet Underground",
    album: "White Light/White Heat",
    released: "1968-01-30",
    sections: ["experimental-rock"],
    cover: MM + "White Light-White Heat.jpg",
    link: "",
    spotify: "spotify:album:0HHmJpwOXXRJu9HI9iQiEO" },
  { artist: "Nas",
    album: "Illmatic",
    released: "1994-04-19",
    sections: ["hip-hop"],
    cover: MM + "Illmatic.jpg",
    link: "",
    spotify: "spotify:album:3kEtdS2pH6hKcMU9Wioob1" },
  { artist: "Wu-Tang Clan",
    album: "Enter the Wu-Tang (36 Chambers)",
    released: "1993-11-09",
    sections: ["hip-hop"],
    cover: MM + "Enter the Wu-Tang (36 Chambers).jpg",
    link: "",
    spotify: "spotify:album:6acGx168JViE5LLFR1rGRE" },
  { artist: "A Tribe Called Quest",
    album: "The Low End Theory",
    released: "1991-09-24",
    sections: ["hip-hop"],
    cover: MM + "The Low End Theory.png",
    link: "",
    spotify: "spotify:album:1p12OAWwudgMqfMzjMvl2a" },
  { artist: "Madvillain",
    album: "Madvillainy",
    released: "2004-03-23",
    sections: ["hip-hop"],
    cover: MM + "Madvillainy.png",
    link: "",
    spotify: "spotify:album:19bQiwEKhXUBJWY6oV3KZk" },
  { artist: "De La Soul",
    album: "3 Feet High and Rising",
    released: "1989-03-03",
    sections: ["hip-hop"],
    cover: MM + "3 Feet High And Rising.jpg",
    link: "",
    spotify: "spotify:album:34LxHI9x14qXUOS8AWRrYD" },
  { artist: "Public Enemy",
    album: "It Takes a Nation of Millions to Hold Us Back",
    released: "1988-06-28",
    sections: ["hip-hop/conscious"],
    cover: MM + "It Takes a Nation of Millions to Hold Us Back.jpg",
    link: "",
    spotify: "spotify:album:1Rj1daFzMlYzLv7lJl14hz" },
  { artist: "Public Enemy",
    album: "Fear of a Black Planet",
    released: "1990-04-10",
    sections: ["hip-hop/conscious"],
    cover: MM + "Fear Of A Black Planet.jpg",
    link: "",
    spotify: "spotify:album:0aFNb4RDk2hmKKLa0bzXNz" },
  { artist: "Black Star",
    album: "Mos Def & Talib Kweli Are Black Star",
    released: "1998-09-29",
    sections: ["hip-hop/conscious"],
    cover: MM + "Mos Def & Talib Kweli Are Black Star.jpg",
    link: "",
    spotify: "spotify:album:6GRzmk9UGL7odxprOPop1Q" },
  { artist: "Kendrick Lamar",
    album: "To Pimp a Butterfly",
    released: "2015-03-15",
    sections: ["hip-hop/conscious"],
    cover: MM + "To Pimp a Butterfly.png",
    link: "",
    spotify: "spotify:album:7ycBtnsMtyVbbwTfJwRjSP" },
  { artist: "Death Grips",
    album: "The Money Store",
    released: "2012-04-24",
    sections: ["hip-hop/experimental"],
    cover: MM + "The Money Store.jpg",
    link: "",
    spotify: "spotify:album:1PQDjdBpHPikAodJqjzm6a" },
  { artist: "DJ Shadow",
    album: "Endtroducing.....",
    released: "1996-09-16",
    sections: ["hip-hop/experimental", "electronic/trip-hop"],
    cover: MM + "Endtroducing......jpg",
    link: "",
    spotify: "spotify:album:4tUVkNYSFrrEqqrxBQW9PN" },
  { artist: "Kraftwerk",
    album: "Trans-Europe Express",
    released: "1977-03-01",
    sections: ["electronic"],
    cover: MM + "Trans-Europe Express.jpg",
    link: "",
    spotify: "spotify:album:0HHRIVjvBcnTepfeRVgS2f" },
  { artist: "Daft Punk",
    album: "Discovery",
    released: "2001-03-12",
    sections: ["electronic/dance"],
    cover: MM + "Discovery.png",
    link: "",
    spotify: "spotify:album:2noRn2Aes5aoNVsU6iWThc" },
  { artist: "The Chemical Brothers",
    album: "Dig Your Own Hole",
    released: "1997-04-07",
    sections: ["electronic/dance"],
    cover: MM + "Dig Your Own Hole.jpg",
    link: "",
    spotify: "spotify:album:0FjHy5dCyVROqDUl6f2VTK" },
  { artist: "Burial",
    album: "Untrue",
    released: "2007-11-05",
    sections: ["electronic/bass"],
    cover: MM + "Untrue.jpg",
    link: "",
    spotify: "spotify:album:1iRPiEYHIX2zpF8lkW54SK" },
  { artist: "Massive Attack",
    album: "Blue Lines",
    released: "1991-04-08",
    sections: ["electronic/trip-hop"],
    cover: MM + "Blue Lines.jpg",
    link: "",
    spotify: "spotify:album:5mAPk4qeNqVLtNydaWbWlf" },
  { artist: "Massive Attack",
    album: "Mezzanine",
    released: "1998-04-20",
    sections: ["electronic/trip-hop"],
    cover: MM + "Mezzanine.png",
    link: "",
    spotify: "spotify:album:49MNmJhZQewjt06rpwp6QR" },
  { artist: "Portishead",
    album: "Dummy",
    released: "1994-08-22",
    sections: ["electronic/trip-hop"],
    cover: MM + "Dummy.png",
    link: "",
    spotify: "spotify:album:3539EbNgIdEDGBKkUf4wno" },
  { artist: "Portishead",
    album: "Portishead",
    released: "1997-09-16",
    sections: ["electronic/trip-hop"],
    cover: MM + "Portishead.png",
    link: "",
    spotify: "spotify:album:3G36754KQVLyGuskraEAVA" },
  { artist: "Tricky",
    album: "Maxinquaye",
    released: "1995-02-20",
    sections: ["electronic/trip-hop"],
    cover: MM + "Maxinquaye.jpg",
    link: "",
    spotify: "spotify:album:7qlZpMib7D0riFPQ5JHDT8" },
  { artist: "Front 242",
    album: "Front by Front",
    released: "1988-11-01",
    sections: ["industrial"],
    cover: MM + "Front By Front.png",
    link: "",
    spotify: "spotify:album:3bJDzdsqXwjo9EXupegwIR" },
  { artist: "Ministry",
    album: "The Land of Rape and Honey",
    released: "1988-10-11",
    sections: ["industrial"],
    cover: MM + "The Land Of Rape And Honey.jpg",
    link: "",
    spotify: "spotify:album:6TyCJQqyB8OZLhUEPCNgNT" },
  { artist: "KMFDM",
    album: "Nihil",
    released: "1995-04-04",
    sections: ["industrial"],
    cover: MM + "Nihil.jpg",
    link: "",
    spotify: "spotify:album:47Z7zIEHWy2ZQQzmg6B1w5" },
  { artist: "Nine Inch Nails",
    album: "Broken",
    released: "1992-09-22",
    type: "EP",
    sections: ["industrial"],
    cover: MM + "Broken.png",
    link: "",
    spotify: "spotify:album:4jyWDa1yM9ul7zgUdR80hw" },
  { artist: "Nine Inch Nails",
    album: "The Downward Spiral",
    released: "1994-03-08",
    sections: ["industrial"],
    cover: MM + "The Downward Spiral.png",
    link: "",
    spotify: "spotify:album:3nJnyDV8fwFpffo0EyHQto" },
  { artist: "Miles Davis",
    album: "Birth of the Cool",
    released: "1957-02-01",
    sections: ["jazz"],
    cover: MM + "Birth of the Cool.jpg",
    link: "",
    spotify: "spotify:album:0QWea2w5Y6pSoSWHuc7JMf" },
  { artist: "Miles Davis",
    album: "Kind of Blue",
    released: "1959-08-17",
    sections: ["jazz"],
    cover: MM + "Kind Of Blue.jpg",
    link: "",
    spotify: "spotify:album:1weenld61qoidwYuZ1GESA" },
  { artist: "Miles Davis",
    album: "In a Silent Way",
    released: "1969-07-30",
    sections: ["jazz"],
    cover: MM + "In A Silent Way.jpg",
    link: "",
    spotify: "spotify:album:0Hs3BomCdwIWRhgT57x22T" },
  { artist: "Miles Davis",
    album: "Bitches Brew",
    released: "1970-03-30",
    sections: ["jazz"],
    cover: MM + "Bitches Brew.jpg",
    link: "",
    spotify: "spotify:album:3Q0zkOZEOC855ErOOJ1AdO" },
  { artist: "John Coltrane",
    album: "Giant Steps",
    released: "1960-02-01",
    sections: ["jazz"],
    cover: MM + "Giant Steps.jpg",
    link: "",
    spotify: "spotify:album:7MBQWjukLxXZYvQ8vzEH7t" },
  { artist: "John Coltrane",
    album: "A Love Supreme",
    released: "1965-02-01",
    sections: ["jazz"],
    cover: MM + "A Love Supreme.jpg",
    link: "",
    spotify: "spotify:album:7Eoz7hJvaX1eFkbpQxC5PA" },
  { artist: "Charles Mingus",
    album: "Mingus Ah Um",
    released: "1959-10-01",
    sections: ["jazz"],
    cover: MM + "Mingus Ah Um.jpg",
    link: "",
    spotify: "spotify:album:7pojWP7x9uEFSJgw765khA" },
  { artist: "Ornette Coleman",
    album: "The Shape of Jazz to Come",
    released: "1959-11-01",
    sections: ["jazz"],
    cover: MM + "The Shape of Jazz to Come.jpg",
    link: "",
    spotify: "spotify:album:2iPH3iUmpa9ufIpwY76keF" },
  { artist: "Stan Getz and João Gilberto",
    album: "Getz/Gilberto",
    released: "1964-03-01",
    sections: ["jazz", "latin"],
    cover: MM + "Getz-Gilberto.jpg",
    link: "",
    spotify: "spotify:album:73ZRKdD3Ds43IjHrhKgucY" },
  { artist: "Iron Maiden",
    album: "The Number of the Beast",
    released: "1982-03-22",
    sections: ["metal/traditional"],
    cover: MM + "The Number of the Beast.jpg",
    link: "",
    spotify: "spotify:album:33d72N71hl9bXwT4zAcqUy" },
  { artist: "Judas Priest",
    album: "British Steel",
    released: "1980-04-14",
    sections: ["metal/traditional"],
    cover: MM + "British Steel.jpg",
    link: "",
    spotify: "spotify:album:5bqtZRbUZUxUps8mrO9tGY" },
  { artist: "Black Sabbath",
    album: "Black Sabbath",
    released: "1970-02-13",
    sections: ["metal/traditional"],
    cover: MM + "Black Sabbath.png",
    link: "",
    spotify: "spotify:album:4ZLy3U2q17Yjw7jkjXPJQj" },
  { artist: "Black Sabbath",
    album: "Paranoid",
    released: "1970-09-18",
    sections: ["metal/traditional"],
    cover: MM + "Paranoid.png",
    link: "",
    spotify: "spotify:album:6r7LZXAVueS5DqdrvXJJK7" },
  { artist: "Metallica",
    album: "Ride the Lightning",
    released: "1984-07-27",
    sections: ["metal/thrash"],
    cover: MM + "Ride the Lightning.png",
    link: "",
    spotify: "spotify:album:1nTvIQEXvygqSIqc2vuwAz" },
  { artist: "Metallica",
    album: "Master of Puppets",
    released: "1986-03-03",
    sections: ["metal/thrash"],
    cover: MM + "Master of Puppets.png",
    link: "",
    spotify: "spotify:album:5gzLOflH95LkKYE6XSXE9k" },
  { artist: "Metallica",
    album: "...And Justice for All",
    released: "1988-09-07",
    sections: ["metal/thrash"],
    cover: MM + "And Justice For All.jpg",
    link: "",
    spotify: "spotify:album:4Cn4T0onWhfJZwWVzU5a2t" },
  { artist: "Slayer",
    album: "Reign in Blood",
    released: "1986-10-07",
    sections: ["metal/thrash"],
    cover: MM + "Reign in Blood.jpg",
    link: "",
    spotify: "spotify:album:2DumvqHl78bNXuvU9kQfPN" },
  { artist: "Megadeth",
    album: "Peace Sells... but Who's Buying?",
    released: "1986-09-19",
    sections: ["metal/thrash"],
    cover: MM + "Peace Sells... But Who's Buying-.jpg",
    link: "",
    spotify: "spotify:album:4U8ZF5zDIRy4lBnnXBN2uO" },
  { artist: "Megadeth",
    album: "Rust in Peace",
    released: "1990-09-24",
    sections: ["metal/thrash"],
    cover: MM + "Rust In Peace.jpg",
    link: "",
    spotify: "spotify:album:4e6ML9RBhDyyKTaTwbiRZv" },
  { artist: "Carcass",
    album: "Heartwork",
    released: "1993-10-18",
    sections: ["metal/death"],
    cover: MM + "Heartwork.jpg",
    link: "",
    spotify: "spotify:album:3WUGsnZVtQyc2miaUQdLpI" },
  { artist: "Napalm Death",
    album: "Scum",
    released: "1987-07-01",
    sections: ["metal/death"],
    cover: MM + "Scum.png",
    link: "",
    spotify: "spotify:album:51wqCUWehVrNj2Ltc83zJu" },
  { artist: "At the Gates",
    album: "Slaughter of the Soul",
    released: "1995-11-14",
    sections: ["metal/death"],
    cover: MM + "Slaughter of the Soul.png",
    link: "",
    spotify: "spotify:album:1m0px7K5tJndjxU6RIuL8U" },
  { artist: "Deafheaven",
    album: "Sunbather",
    released: "2013-06-11",
    sections: ["metal/black"],
    cover: MM + "Sunbather.jpg",
    link: "",
    spotify: "spotify:album:2kKXGWaCEl06EKZ4DxBJIT" },
  { artist: "Black Sabbath",
    album: "Master of Reality",
    released: "1971-07-21",
    sections: ["metal/doom"],
    cover: MM + "Master of Reality.png",
    link: "",
    spotify: "spotify:album:3zzJ2dFBOcsgdiqQigftrM" },
  { artist: "Electric Wizard",
    album: "Dopethrone",
    released: "2000-09-25",
    sections: ["metal/doom"],
    cover: MM + "Dopethrone.jpg",
    link: "",
    spotify: "spotify:album:1AxwLCMtx8rnIxkFQKU2LO" },
  { artist: "Neurosis",
    album: "Through Silver in Blood",
    released: "1996-04-02",
    sections: ["metal/doom"],
    cover: MM + "Through Silver In Blood.jpg",
    link: "",
    spotify: "spotify:album:6HBRtTolIqgDVJXBwtyYPV" },
  { artist: "Converge",
    album: "Jane Doe",
    released: "2001-09-04",
    sections: ["metal/metalcore"],
    cover: MM + "Jane Doe.jpg",
    link: "",
    spotify: "spotify:album:2gtM4m6sglJDrX3toJWZO6" },
  { artist: "Sepultura",
    album: "Chaos A.D.",
    released: "1993-09-01",
    sections: ["metal/groove"],
    cover: MM + "Chaos A.D..jpg",
    link: "",
    spotify: "spotify:album:5r4qa5AIQUVypFRXQzjaiu" },
  { artist: "Rage Against the Machine",
    album: "Rage Against the Machine",
    released: "1992-11-03",
    sections: ["metal/groove"],
    cover: MM + "Rage Against The Machine.png",
    link: "",
    spotify: "spotify:album:4LaRYkT4oy47wEuQgkLBul" },
  { artist: "System of a Down",
    album: "Toxicity",
    released: "2001-09-04",
    sections: ["metal/groove"],
    cover: MM + "Toxicity.png",
    link: "",
    spotify: "spotify:album:6jWde94ln40epKIQCd8XUh" },
  { artist: "Tool",
    album: "Ænima",
    released: "1996-09-17",
    sections: ["metal/groove"],
    cover: MM + "AEima.jpg",
    link: "",
    spotify: "spotify:album:6yWMN087PgSimbcVmHLEwG" },
  { artist: "Joy Division",
    album: "Unknown Pleasures",
    released: "1979-06-15",
    sections: ["post-punk"],
    cover: MM + "Unknown Pleasures.jpg",
    link: "",
    spotify: "spotify:album:5Dgqy4bBg09Rdw7CQM545s" },
  { artist: "Joy Division",
    album: "Closer",
    released: "1980-07-18",
    sections: ["post-punk"],
    cover: MM + "Closer.jpg",
    link: "",
    spotify: "spotify:album:0KBdfMTMxi0oD1oVqApTjr" },
  { artist: "The Cure",
    album: "Pornography",
    released: "1982-05-03",
    sections: ["post-punk"],
    cover: MM + "Pornography.png",
    link: "",
    spotify: "spotify:album:33TDfmEXufojT6jxgb3BTK" },
  { artist: "The Cure",
    album: "Disintegration",
    released: "1989-05-02",
    sections: ["post-punk"],
    cover: MM + "Disintegration.jpg",
    link: "",
    spotify: "spotify:album:0A13JySVHzBoRZFk2o89Wl" },
  { artist: "Bauhaus",
    album: "In the Flat Field",
    released: "1980-11-03",
    sections: ["post-punk", "halloween"],
    cover: MM + "In the Flat Field.jpg",
    link: "",
    spotify: "spotify:album:4hPJRedKOmbvKnLdzV9w1w" },
  { artist: "Siouxsie and the Banshees",
    album: "Juju",
    released: "1981-06-19",
    sections: ["post-punk"],
    cover: MM + "Juju.jpg",
    link: "",
    spotify: "spotify:album:5OEum65e1HMGX51Ifu51Wb" },
  { artist: "Gang of Four",
    album: "Entertainment!",
    released: "1979-09-25",
    sections: ["post-punk"],
    cover: MM + "Entertainment!.jpg",
    link: "",
    spotify: "spotify:album:7LMOo068Ndv0wjTGUDtYqK" },
  { artist: "Talking Heads",
    album: "Remain in Light",
    released: "1980-10-08",
    sections: ["post-punk"],
    cover: MM + "Remain In Light.png",
    link: "",
    spotify: "spotify:album:1JvXxLsm0PxlGH4LXzqMGq" },
  { artist: "Ramones",
    album: "Ramones",
    released: "1976-04-23",
    sections: ["punk/punk-rock"],
    cover: MM + "Ramones.jpg",
    link: "",
    spotify: "spotify:album:3ToX9inehiXTv17hpaOyie" },
  { artist: "Ramones",
    album: "Rocket to Russia",
    released: "1977-11-04",
    sections: ["punk/punk-rock"],
    cover: MM + "Rocket To Russia.jpg",
    link: "",
    spotify: "spotify:album:3SBh2kzao9z3gLCzOV45ho" },
  { artist: "Sex Pistols",
    album: "Never Mind the Bollocks, Here's the Sex Pistols",
    released: "1977-10-28",
    sections: ["punk/punk-rock"],
    cover: MM + "Never Mind the Bollocks, Here's the Sex Pistols.png",
    link: "",
    spotify: "spotify:album:5fxYu3rqjCNTSPKN8mtEl2" },
  { artist: "The Clash",
    album: "The Clash",
    released: "1977-04-08",
    sections: ["punk/punk-rock"],
    cover: MM + "The Clash.jpg",
    link: "",
    spotify: "spotify:album:49kzgMsxHU5CTeb2XmFHjo" },
  { artist: "The Clash",
    album: "London Calling",
    released: "1979-12-14",
    sections: ["punk/punk-rock", "post-punk"],
    cover: MM + "London Calling.jpg",
    link: "",
    spotify: "spotify:album:6FCzvataOZh68j8OKzOt9a" },
  { artist: "Wire",
    album: "Pink Flag",
    released: "1977-12-01",
    sections: ["punk/punk-rock"],
    cover: MM + "Pink Flag.jpg",
    link: "",
    spotify: "spotify:album:4WXqZZ28geJSPtqLcCF56L" },
  { artist: "Black Flag",
    album: "Damaged",
    released: "1981-12-05",
    sections: ["punk/hardcore"],
    cover: MM + "Damaged.jpg",
    link: "",
    spotify: "spotify:album:34aFnrFRBlErcbU6moRZR3" },
  { artist: "Bad Brains",
    album: "Bad Brains",
    released: "1982-02-05",
    sections: ["punk/hardcore"],
    cover: MM + "Bad Brains.png",
    link: "",
    spotify: "spotify:album:4NpepcKo9rQ8nkdCB6iWMP" },
  { artist: "Minor Threat",
    album: "Complete Discography",
    released: "1989-01-01",
    sections: ["punk/hardcore"],
    cover: MM + "Complete Discography.jpg",
    link: "",
    spotify: "spotify:album:6Sty6rLnMTXFjKxKUZEfmy" },
  { artist: "Hüsker Dü",
    album: "Zen Arcade",
    released: "1984-07-01",
    sections: ["punk/hardcore"],
    cover: MM + "Zen Arcade.jpg",
    link: "",
    spotify: "spotify:album:0J1DP5GvKrzWumwzlcFhLc" },
  { artist: "Fugazi",
    album: "Repeater",
    released: "1990-04-19",
    sections: ["punk/hardcore"],
    cover: MM + "Repeater.jpg",
    link: "",
    spotify: "spotify:album:6JbGZGta38AArBgflt024C" },
  { artist: "Refused",
    album: "The Shape of Punk to Come",
    released: "1998-10-27",
    sections: ["punk/hardcore"],
    cover: MM + "The Shape of Punk to Come.jpg",
    link: "",
    spotify: "spotify:album:2Us9qPHLvLoTl6HkYAPcz2" },
  { artist: "Misfits",
    album: "Walk Among Us",
    released: "1982-03-01",
    sections: ["punk/hardcore", "halloween"],
    cover: MM + "Walk Among Us.jpg",
    link: "" },
  { artist: "Marvin Gaye",
    album: "What's Going On",
    released: "1971-05-21",
    sections: ["rnb"],
    cover: MM + "What's Going On.jpg",
    link: "",
    spotify: "spotify:album:2v6ANhWhZBUKkg6pJJBs3B" },
  { artist: "Marvin Gaye",
    album: "Let's Get It On",
    released: "1973-08-28",
    sections: ["rnb"],
    cover: MM + "Let's Get it On.png",
    link: "",
    spotify: "spotify:album:6AmnVWOxXYucWxgidEgwhy" },
  { artist: "Stevie Wonder",
    album: "Innervisions",
    released: "1973-08-03",
    sections: ["rnb"],
    cover: MM + "Innervisions.jpg",
    link: "",
    spotify: "spotify:album:5jgI8Eminx9MmLBontDWq8" },
  { artist: "Stevie Wonder",
    album: "Songs in the Key of Life",
    released: "1976-09-28",
    sections: ["rnb"],
    cover: MM + "Songs in the Key of Life.jpg",
    link: "",
    spotify: "spotify:album:6YUCc2RiXcEKS9ibuZxjt0" },
  { artist: "Funkadelic",
    album: "Maggot Brain",
    released: "1971-07-12",
    sections: ["rnb"],
    cover: MM + "Maggot Brain.jpg",
    link: "",
    spotify: "spotify:album:3ywVzrwMQ3Kq43N9zBdBQm" },
  { artist: "Aretha Franklin",
    album: "I Never Loved a Man the Way I Love You",
    released: "1967-03-10",
    sections: ["rnb"],
    cover: MM + "I Never Loved a Man the Way I Love You.png",
    link: "",
    spotify: "spotify:album:5WndWfzGwCkHzAbQXVkg2V" },
  { artist: "D'Angelo",
    album: "Brown Sugar",
    released: "1995-07-03",
    sections: ["rnb/neo-soul"],
    cover: MM + "Brown Sugar.jpg",
    link: "",
    spotify: "spotify:album:4HTVABUq8amDUxBv3zJbX4" },
  { artist: "D'Angelo",
    album: "Voodoo",
    released: "2000-01-25",
    sections: ["rnb/neo-soul"],
    cover: MM + "Voodoo.jpg",
    link: "",
    spotify: "spotify:album:2lO9yuuIDgBpSJzxTh3ai8" },
  { artist: "Erykah Badu",
    album: "Baduizm",
    released: "1997-02-11",
    sections: ["rnb/neo-soul"],
    cover: MM + "Baduizm.jpg",
    link: "",
    spotify: "spotify:album:3qr4pTBWEU1SVf01j6RAx3" },
  { artist: "Lauryn Hill",
    album: "The Miseducation of Lauryn Hill",
    released: "1998-08-25",
    sections: ["rnb/neo-soul"],
    cover: MM + "The Miseducation of Lauryn Hill.jpg",
    link: "",
    spotify: "spotify:album:1BZoqf8Zje5nGdwZhOjAtD" },
  { artist: "The Specials",
    album: "The Specials",
    released: "1979-10-19",
    sections: ["ska"],
    cover: MM + "The Specials.jpg",
    link: "",
    spotify: "spotify:album:2OHPxPTasGkolt8lFDxCpE" },
  { artist: "The Beat",
    album: "I Just Can't Stop It",
    released: "1980-05-23",
    sections: ["ska"],
    cover: MM + "I Just Can’t Stop It.jpg",
    link: "",
    spotify: "spotify:album:08zjJfP4f6cXGxscvztbvh" },
  { artist: "Operation Ivy",
    album: "Energy",
    released: "1989-05-28",
    sections: ["ska"],
    cover: MM + "Energy.jpg",
    link: "",
    spotify: "spotify:album:2Rv1kIWFeIYeq8kAtdhY6m" },
  { artist: "Catch 22",
    album: "Keasbey Nights",
    released: "1998-03-24",
    sections: ["ska"],
    cover: MM + "Keasbey Nights.jpg",
    link: "",
    spotify: "spotify:album:2sFPd4EWqI4x6RsaeMqA8a" },
  { artist: "Bob Dylan",
    album: "Bringing It All Back Home",
    released: "1965-03-25",
    sections: ["folk"],
    cover: MM + "Bringing It All Back Home.jpg",
    link: "",
    spotify: "spotify:album:1lPoRKSgZHQAYXxzBsOQ7v" },
  { artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    released: "1965-08-30",
    sections: ["folk"],
    cover: MM + "Highway 61 Revisited.jpg",
    link: "",
    spotify: "spotify:album:6YabPKtZAjxwyWbuO9p4ZD" },
  { artist: "Bob Dylan",
    album: "Blonde on Blonde",
    released: "1966-06-20",
    sections: ["folk"],
    cover: MM + "Blonde On Blonde.jpg",
    link: "",
    spotify: "spotify:album:4NP1rhnsPdYpnyJP0p0k0L" },
  { artist: "Bob Dylan",
    album: "Blood on the Tracks",
    released: "1975-01-20",
    sections: ["folk"],
    cover: MM + "Blood On The Tracks.jpg",
    link: "",
    spotify: "spotify:album:4WD4pslu83FF6oMa1e19mF" },
  { artist: "Joni Mitchell",
    album: "Blue",
    released: "1971-06-22",
    sections: ["folk"],
    cover: MM + "Blue.jpg",
    link: "" },
  { artist: "Neil Young",
    album: "After the Gold Rush",
    released: "1970-09-19",
    sections: ["folk"],
    cover: MM + "After The Gold Rush.jpg",
    link: "",
    spotify: "spotify:album:5EVlXlHbRQI8ybuNt4ArXI" },
  { artist: "The Band",
    album: "Music from Big Pink",
    released: "1968-07-01",
    sections: ["folk"],
    cover: MM + "Music From Big Pink.jpg",
    link: "",
    spotify: "spotify:album:4vXFiaDS8zuEl5bOUbW53x" },
  { artist: "Robert Johnson",
    album: "King of the Delta Blues Singers",
    released: "1961-01-01",
    sections: ["blues"],
    cover: MM + "King Of The Delta Blues Singers.jpg",
    link: "",
    spotify: "spotify:album:2IWaNq5o4tG1w6yxve5BMU" },
  { artist: "Elvis Presley",
    album: "The Sun Sessions",
    released: "1976-03-21",
    sections: ["blues"],
    cover: MM + "The Sun Sessions.jpg",
    link: "" },
  { artist: "Led Zeppelin",
    album: "Led Zeppelin",
    released: "1969-01-12",
    sections: ["rock"],
    cover: MM + "Led Zeppelin.jpg",
    link: "",
    spotify: "spotify:album:3ycjBixZf7S3WpC5WZhhUK" },
  { artist: "Led Zeppelin",
    album: "Led Zeppelin II",
    released: "1969-10-22",
    sections: ["rock"],
    cover: MM + "Led Zeppelin II.jpg",
    link: "",
    spotify: "spotify:album:58MQ0PLijVHePUonQlK76Y" },
  { artist: "Led Zeppelin",
    album: "Untitled aka Led Zeppelin IV",
    released: "1971-11-08",
    sections: ["rock"],
    cover: MM + "Led Zeppelin IV.jpg",
    link: "",
    spotify: "spotify:album:5EyIDBAqhnlkAHqvPRwdbX" },
  { artist: "The Rolling Stones",
    album: "Beggars Banquet",
    released: "1968-12-06",
    sections: ["rock"],
    cover: MM + "Beggars Banquet.jpg",
    link: "",
    spotify: "spotify:album:6OHri5qNxwCdVSdyCslspd" },
  { artist: "The Rolling Stones",
    album: "Let It Bleed",
    released: "1969-11-28",
    sections: ["rock"],
    cover: MM + "Let It Bleed.jpg",
    link: "",
    spotify: "spotify:album:4l4u9e9jSbotSXNjYfOugy" },
  { artist: "The Rolling Stones",
    album: "Exile on Main St.",
    released: "1972-05-12",
    sections: ["rock"],
    cover: MM + "Exile On Main St..jpg",
    link: "",
    spotify: "spotify:album:5U4dnRZsfW8NmwBBkELFPh" },
  { artist: "Kate Bush",
    album: "Hounds of Love",
    released: "1985-09-16",
    sections: ["pop"],
    cover: MM + "Hounds Of Love.png",
    link: "",
    spotify: "spotify:album:5G5UwqPsxDKpxJLX4xsyuh" },
  { artist: "Depeche Mode",
    album: "Violator",
    released: "1990-03-19",
    sections: ["pop"],
    cover: MM + "Violator.png",
    link: "",
    spotify: "spotify:album:5g3Yi15plTSMaq6tYiuw8p" },
  { artist: "Björk",
    album: "Post",
    released: "1995-06-07",
    sections: ["pop"],
    cover: MM + "Post.png",
    link: "",
    spotify: "spotify:album:2Ul7B1LEHxXzYubtkTMENs" },
  { artist: "Björk",
    album: "Homogenic",
    released: "1997-09-20",
    sections: ["pop", "electronic/idm"],
    cover: MM + "Homogenic.jpg",
    link: "",
    spotify: "spotify:album:0HMsmYvoT1h2x1C4di5faf" }
];
