/* Indie Rock / Alternative Rock
   -----------------------------
   One line per album. Copy the blank line, fill in the quotes, and keep
   the comma at the end. The blank line itself is ignored.

     artist    "Metallica"
     album     "Master of Puppets"
     released  "1986"  or  "1986-03-03"     (used by the release-date sorts)
     spotify   the album's Spotify link      (Play opens it, and its cover is used)

   Optional extras, added inside the { } with a comma before each:
     pick: true                    Staff Pick in this room
     note: "..."                   handwritten card under a Staff Pick
     type: "EP"                    small badge on the cover
     cover: "some-file.jpg"        use this image from images/covers/ instead (see below)
     link: "https://..."           Play opens this instead, for albums not on Spotify
     sortAs: "Dylan, Bob"          file it under a different name

   Covers come from Spotify by themselves. For an album that isn't on Spotify
   (or to use a different picture), save the image in images/covers/ named
   exactly  Artist - Album.jpg  (or .png), e.g.
   images/covers/Chuck Berry - Chuck Berry's Golden Decade.jpg
   Leave out characters Windows won't allow in file names ( \ / : * ? " < > | ).
   A cover: "..." on the line beats everything; a saved Artist - Album file is
   used when there's no Spotify cover; Melodic Mosaic's cover after that.
*/

shelf([

  { artist: "...And You Will Know Us by the Trail of Dead", album: "Source Tags & Codes", released: "2002", spotify: "" },
  { artist: "Alex G", album: "God Save the Animals", released: "2022", spotify: "" },
  { artist: "Alvvays", album: "Blue Rev", released: "2022", spotify: "" },
  { artist: "American Music Club", album: "Everclear", released: "1991", spotify: "" },
  { artist: "Angel Olsen", album: "All Mirrors", released: "2019", spotify: "https://open.spotify.com/album/0RedX0LZkGUFoRwFntAaI0" },
  { artist: "Angel Olsen", album: "Burn Your Fire for No Witness", released: "2014", spotify: "" },
  { artist: "Angel Olsen", album: "My Woman", released: "2016", spotify: "https://open.spotify.com/album/5M8xQaQZuW2LZGVXZ3mlKN" },
  { artist: "Animal Collective", album: "Feels", released: "2005", spotify: "" },
  { artist: "Animal Collective", album: "Merriweather Post Pavilion", released: "2009", spotify: "" },
  { artist: "Animal Collective", album: "Strawberry Jam", released: "2007", spotify: "" },
  { artist: "Animal Collective", album: "Sung Tongs", released: "2004", spotify: "" },
  { artist: "Arcade Fire", album: "Funeral", released: "2004", spotify: "https://open.spotify.com/album/6ZB8qaR9JNuS0Q0bG1nbcH" },
  { artist: "Arcade Fire", album: "Neon Bible", released: "2007", spotify: "" },
  { artist: "Arcade Fire", album: "Reflektor", released: "2013", spotify: "" },
  { artist: "Arcade Fire", album: "The Suburbs", released: "2010", spotify: "https://open.spotify.com/album/3DrgM5X3yX1JP1liNLAOHI" },
  { artist: "Arctic Monkeys", album: "AM", released: "2013", spotify: "https://open.spotify.com/album/78bpIziExqiI9qztvNFlQu" },
  { artist: "Arctic Monkeys", album: "Whatever People Say I Am, That's What I'm Not", released: "2006", spotify: "https://open.spotify.com/album/50Zz8CkIhATKUlQMbHO3k1" },
  { artist: "Art Brut", album: "Bang Bang Rock & Roll", released: "2005", spotify: "" },
  { artist: "Beach House", album: "Bloom", released: "2012", spotify: "" },
  { artist: "Beach House", album: "Teen Dream", released: "2010", spotify: "https://open.spotify.com/album/4sYpTER2iT2Y7Kf4VsfUne" },
  { artist: "Beat Happening", album: "Beat Happening", released: "1984", spotify: "" },
  { artist: "Beck", album: "Mellow Gold", released: "1994", spotify: "https://open.spotify.com/album/0iIGP4Sxw3KR4OCFv2yvz8" },
  { artist: "Beck", album: "Midnite Vultures", released: "1999", spotify: "" },
  { artist: "Beck", album: "Odelay", released: "1996", spotify: "https://open.spotify.com/album/1Pus5h1qGedCn4CtOuPVtp" },
  { artist: "Beck", album: "The Information", released: "2006", spotify: "" },
  { artist: "Belle and Sebastian", album: "If You're Feeling Sinister", released: "1996", spotify: "https://open.spotify.com/album/3e9VtbXnl6tqrFKrnNyxaI" },
  { artist: "Belly", album: "Star", released: "1993", spotify: "" },
  { artist: "Ben Folds Five", album: "Whatever and Ever Amen", released: "1997", spotify: "https://open.spotify.com/album/3oz8kworUyU7oXjaEVhDsZ" },
  { artist: "Big Star", album: "Third (Sister Lovers)", released: "1978", spotify: "https://open.spotify.com/album/0NJYYhhvOATAkUipSJEBDb" },
  { artist: "Blur", album: "13", released: "1999", spotify: "https://open.spotify.com/album/5YuZ4DjvtZBywtIbHIqtGJ" },
  { artist: "Blur", album: "Modern Life Is Rubbish", released: "1993", spotify: "" },
  { artist: "Blur", album: "Parklife", released: "1994", spotify: "https://open.spotify.com/album/0YS25Dr3hMtMFlVTfuvzl4" },
  { artist: "Bon Iver", album: "Bon Iver", released: "2011", spotify: "https://open.spotify.com/album/1JlvIsP2f6ckoa62aN7kLn" },
  { artist: "Broken Social Scene", album: "You Forgot It in People", released: "2002", spotify: "" },
  { artist: "Built to Spill", album: "Keep It Like a Secret", released: "1999", spotify: "" },
  { artist: "Built to Spill", album: "Perfect from Now On", released: "1997", spotify: "" },
  { artist: "Car Seat Headrest", album: "Teens of Denial", released: "2016", spotify: "https://open.spotify.com/album/26DseQO366JfXwIP7dIgQj" },
  { artist: "Circulatory System", album: "Circulatory System", released: "2001", spotify: "" },
  { artist: "Clinic", album: "Internal Wrangler", released: "2000", spotify: "" },
  { artist: "Coldplay", album: "A Rush of Blood to the Head", released: "2002", spotify: "https://open.spotify.com/album/0RHX9XECH8IVI3LNgWDpmQ" },
  { artist: "Coldplay", album: "Parachutes", released: "2000", spotify: "https://open.spotify.com/album/6ZG5lRT77aJ3btmArcykra" },
  { artist: "Coldplay", album: "Viva la Vida or Death and All His Friends", released: "2008", spotify: "https://open.spotify.com/album/1CEODgTmTwLyabvwd7HBty" },
  { artist: "Cornelius", album: "Fantasma", released: "1997", spotify: "" },
  { artist: "Cornershop", album: "When I Was Born for the 7th Time", released: "1997", spotify: "" },
  { artist: "Courtney Barnett", album: "Sometimes I Sit and Think, and Sometimes I Just Sit", released: "2015", spotify: "" },
  { artist: "Crowded House", album: "Crowded House", released: "1986", spotify: "https://open.spotify.com/album/0Vw2BOifLhBx5mvnepOGVf" },
  { artist: "Deerhunter", album: "Halcyon Digest", released: "2010", spotify: "https://open.spotify.com/album/1HUMjB15ARg96KIypcGzYY" },
  { artist: "Deerhunter", album: "Microcastle", released: "2008", spotify: "" },
  { artist: "Deerhunter", album: "Weird Era Cont.", released: "2008", spotify: "" },
  { artist: "Dinosaur Jr.", album: "Green Mind", released: "1991", spotify: "" },
  { artist: "Dirty Projectors", album: "Bitte Orca", released: "2009", spotify: "" },
  { artist: "Eels", album: "Electro-Shock Blues", released: "1998", spotify: "" },
  { artist: "Everything Everything", album: "Get to Heaven", released: "2015", spotify: "" },
  { artist: "Florence and the Machine", album: "Lungs", released: "2009", spotify: "" },
  { artist: "Geese", album: "Getting Killed", released: "2025", spotify: "" },
  { artist: "Girls", album: "Album", released: "2009", spotify: "" },
  { artist: "Girls", album: "Father, Son, Holy Ghost", released: "2011", spotify: "" },
  { artist: "Grandaddy", album: "The Sophtware Slump", released: "2000", spotify: "" },
  { artist: "Grizzly Bear", album: "Shields", released: "2012", spotify: "" },
  { artist: "Grizzly Bear", album: "Veckatimest", released: "2009", spotify: "" },
  { artist: "Grizzly Bear", album: "Yellow House", released: "2006", spotify: "" },
  { artist: "Guided by Voices", album: "Bee Thousand", released: "1994", spotify: "" },
  { artist: "Haim", album: "Women in Music Pt. III", released: "2020", spotify: "" },
  { artist: "Happy Mondays", album: "Pills 'n' Thrills and Bellyaches", released: "1990", spotify: "" },
  { artist: "Imperial Teen", album: "Seasick", released: "1996", spotify: "" },
  { artist: "Jack White", album: "No Name", released: "2024", spotify: "" },
  { artist: "Jeff Buckley", album: "Grace", released: "1994", spotify: "https://open.spotify.com/album/7yQtjAjhtNi76KRu05XWFS" },
  { artist: "The Lemonheads", album: "It's a Shame About Ray", released: "1992", spotify: "" },
  { artist: "Liz Phair", album: "Exile In Guyville", released: "1993", spotify: "https://open.spotify.com/album/7sCpW2cLGcRk1zf9zi0Yqd" },
  { artist: "Manic Street Preachers", album: "Everything Must Go", released: "1996", spotify: "" },
  { artist: "Manic Street Preachers", album: "Generation Terrorists", released: "1992", spotify: "" },
  { artist: "Manic Street Preachers", album: "The Holy Bible", released: "1994", spotify: "" },
  { artist: "Matthew Sweet", album: "100% Fun", released: "1995", spotify: "" },
  { artist: "Meat Puppets", album: "Meat Puppets II", released: "1983", spotify: "" },
  { artist: "Midnight Oil", album: "Blue Sky Mining", released: "1990", spotify: "" },
  { artist: "Midnight Oil", album: "Diesel and Dust", released: "1987", spotify: "https://open.spotify.com/album/243XzHQegX82bPnUVQ0SPV" },
  { artist: "Mitski", album: "Be the Cowboy", released: "2018", spotify: "https://open.spotify.com/album/653wRjqO0GOZPQPcXpeAXD" },
  { artist: "MJ Lenderman", album: "Manning Fireworks", released: "2024", spotify: "" },
  { artist: "Modest Mouse", album: "Good News for People Who Love Bad News", released: "2004", spotify: "" },
  { artist: "Modest Mouse", album: "The Lonesome Crowded West", released: "1997", spotify: "" },
  { artist: "Modest Mouse", album: "The Moon & Antarctica", released: "2000", spotify: "" },
  { artist: "Morphine", album: "Cure for Pain", released: "1993", spotify: "" },
  { artist: "Morrissey", album: "Your Arsenal", released: "1992", spotify: "" },
  { artist: "My Bloody Valentine", album: "Loveless", released: "1991", spotify: "https://open.spotify.com/album/3GH4IiI6jQAIvnHVdb5FB6" },
  { artist: "My Bloody Valentine", album: "m b v", released: "2013", spotify: "" },
  { artist: "My Chemical Romance", album: "The Black Parade", released: "2006", spotify: "https://open.spotify.com/album/0FZK97MXMm5mUQ8mtudjuK" },
  { artist: "My Morning Jacket", album: "Okonokos", released: "2006", spotify: "", type: "Live" },
  { artist: "Neutral Milk Hotel", album: "In the Aeroplane Over the Sea", released: "1998", spotify: "https://open.spotify.com/album/0vVekV45lOaVKs6RZQQNob" },
  { artist: "Oasis", album: "(What's the Story) Morning Glory?", released: "1995", spotify: "https://open.spotify.com/album/2u30gztZTylY4RG7IvfXs8" },
  { artist: "Oasis", album: "Definitely Maybe", released: "1994", spotify: "https://open.spotify.com/album/3AMHMM2aNG6k3d7ybcQ5bY" },
  { artist: "Parquet Courts", album: "Wide Awake!", released: "2018", spotify: "" },
  { artist: "Pavement", album: "Brighten the Corners", released: "1997", spotify: "" },
  { artist: "Pavement", album: "Crooked Rain, Crooked Rain", released: "1994", spotify: "https://open.spotify.com/album/1XFNz6KIvLyIsLFOiLRKqP" },
  { artist: "Pavement", album: "Slanted and Enchanted", released: "1992", spotify: "https://open.spotify.com/album/7o14zVcXSRk7clV6QCEdOD" },
  { artist: "Phoebe Bridgers", album: "Lost Weekend", released: "", spotify: "" },
  { artist: "Phoebe Bridgers", album: "Punisher", released: "2020", spotify: "" },
  { artist: "Pixies", album: "Doolittle", released: "1989", spotify: "https://open.spotify.com/album/0DQyTVcDhK9wm0f6RaErWO" },
  { artist: "Pixies", album: "Surfer Rosa", released: "1988", spotify: "https://open.spotify.com/album/50j4Wm1b9hLpSpPIA39Vp9" },
  { artist: "Pixies", album: "Trompe le Monde", released: "1991", spotify: "" },
  { artist: "PJ Harvey", album: "4-Track Demos", released: "1993", spotify: "" },
  { artist: "PJ Harvey", album: "Dry", released: "1992", spotify: "" },
  { artist: "PJ Harvey", album: "Is This Desire?", released: "1998", spotify: "" },
  { artist: "PJ Harvey", album: "Let England Shake", released: "2011", spotify: "https://open.spotify.com/album/2f8Rfpdol5jrJe3OL4YH6k" },
  { artist: "PJ Harvey", album: "Rid of Me", released: "1993", spotify: "https://open.spotify.com/album/2fDJpBJhtloxzUENHlU9JB" },
  { artist: "PJ Harvey", album: "Stories from the City, Stories from the Sea", released: "2000", spotify: "https://open.spotify.com/album/0hBWhJEmVyNPG2Jq71CJXz" },
  { artist: "PJ Harvey", album: "To Bring You My Love", released: "1995", spotify: "https://open.spotify.com/album/2yMg8ronKfVDHngnlLNnl8" },
  { artist: "Pulp", album: "Different Class", released: "1995", spotify: "https://open.spotify.com/album/3ly9T2L4pqTZijFgQssd3x" },
  { artist: "Pulp", album: "This is Hardcore", released: "1998", spotify: "" },
  { artist: "Queens of the Stone Age", album: "...Like Clockwork", released: "2013", spotify: "https://open.spotify.com/album/06S2JBsr4U1Dz3YaenPdVq" },
  { artist: "Queens of the Stone Age", album: "Queens of the Stone Age", released: "1998", spotify: "" },
  { artist: "Queens of the Stone Age", album: "Rated R", released: "2000", spotify: "" },
  { artist: "R.E.M.", album: "Automatic for the People", released: "1992", spotify: "https://open.spotify.com/album/0BiNb8HYR4JvuxUa31Z58Q" },
  { artist: "R.E.M.", album: "Document", released: "1987", spotify: "https://open.spotify.com/album/6gMv3MgFlieOM6Uz5GZBzy" },
  { artist: "R.E.M.", album: "Monster", released: "1994", spotify: "" },
  { artist: "R.E.M.", album: "Murmur", released: "1983", spotify: "https://open.spotify.com/album/4Mw9Gcu1LT7JaipXdwrq1Q" },
  { artist: "R.E.M.", album: "New Adventures In Hi-Fi", released: "1996", spotify: "" },
  { artist: "R.E.M.", album: "Out of Time", released: "1991", spotify: "https://open.spotify.com/album/4v5hSLj6ClyLqj2nnaPbfD" },
  { artist: "Rachel Chinouriri", album: "Four° in Winter", released: "2021", spotify: "" },
  { artist: "Radiohead", album: "A Moon Shaped Pool", released: "2016", spotify: "" },
  { artist: "Radiohead", album: "Amnesiac", released: "2001", spotify: "https://open.spotify.com/album/1HrMmB5useeZ0F5lHrMvl0" },
  { artist: "Radiohead", album: "Hail to the Thief", released: "2003", spotify: "" },
  { artist: "Radiohead", album: "In Rainbows", released: "2007", spotify: "https://open.spotify.com/album/5vkqYmiPBYLaalcmjujWxK" },
  { artist: "Radiohead", album: "Kid A", released: "2000", spotify: "https://open.spotify.com/album/6GjwtEZcfenmOf6l18N7T7" },
  { artist: "Radiohead", album: "OK Computer", released: "1997", spotify: "https://open.spotify.com/album/6dVIqQ8qmQ5GBnJ9shOYGE" },
  { artist: "Radiohead", album: "The Bends", released: "1995", spotify: "https://open.spotify.com/album/35UJLpClj5EDrhpNIi4DFg" },
  { artist: "Real Estate", album: "Days", released: "2011", spotify: "https://open.spotify.com/album/7e6bDoD8VD0549bu69UTEF" },
  { artist: "Red Hot Chili Peppers", album: "Blood Sugar Sex Magik", released: "1991", spotify: "https://open.spotify.com/album/1DCI2yWmV4UI7Aga71yx9B" },
  { artist: "Regurgitator", album: "Tu-Plang", released: "1996", spotify: "" },
  { artist: "Regurgitator", album: "Unit", released: "1997", spotify: "" },
  { artist: "Robyn Hitchcock and The Egyptians", album: "Perspex Island", released: "1991", spotify: "" },
  { artist: "Santigold", album: "Santogold", released: "2008", spotify: "" },
  { artist: "Sebadoh", album: "Harmacy", released: "1996", spotify: "" },
  { artist: "Semisonic", album: "Feeling Strangely Fine", released: "1998", spotify: "https://open.spotify.com/album/6KaEKR4KsmFWVrb0ktQo2T" },
  { artist: "SF Seals", album: "Truth Walks in Sleepy Shadows", released: "1995", spotify: "" },
  { artist: "Sinéad O'Connor", album: "I Do Not Want What I Haven't Got", released: "1990", spotify: "https://open.spotify.com/album/0fV9DAddjwNZcmCP1Q8b01" },
  { artist: "Sleater-Kinney", album: "Dig Me Out", released: "1997", spotify: "https://open.spotify.com/album/3tshnNFNhHrO6NUQ0BHw42" },
  { artist: "Smog", album: "Dongs of Sevotion", released: "2000", spotify: "" },
  { artist: "Snail Mail", album: "Lush", released: "2018", spotify: "https://open.spotify.com/album/2e48GqjEwCi87gQJanb1bf" },
  { artist: "Spoon", album: "Ga Ga Ga Ga Ga", released: "2007", spotify: "" },
  { artist: "Spoon", album: "Kill the Moonlight", released: "2002", spotify: "" },
  { artist: "Suede", album: "Dog Man Star", released: "1994", spotify: "" },
  { artist: "Suede", album: "Suede", released: "1993", spotify: "" },
  { artist: "Sugar", album: "Copper Blue", released: "1992", spotify: "" },
  { artist: "Super Furry Animals", album: "Rings Around the World", released: "2001", spotify: "" },
  { artist: "Tame Impala", album: "Currents", released: "2015", spotify: "https://open.spotify.com/album/79dL7FLiJFOO0EoehUHQBv" },
  { artist: "Tame Impala", album: "Lonerism", released: "2012", spotify: "https://open.spotify.com/album/3C2MFZ2iHotUQOSBzdSvM7" },
  { artist: "Teenage Fanclub", album: "A Catholic Education", released: "1990", spotify: "" },
  { artist: "Teenage Fanclub", album: "Bandwagonesque", released: "1991", spotify: "" },
  { artist: "The Afghan Whigs", album: "Gentlemen", released: "1993", spotify: "" },
  { artist: "The Beta Band", album: "The Three E.P.'s", released: "1998", spotify: "" },
  { artist: "The Breeders", album: "Last Splash", released: "1993", spotify: "https://open.spotify.com/album/57F44c0MTziVzHPEuJtH9A" },
  { artist: "The Dead Weather", album: "Horehound", released: "2009", spotify: "" },
  { artist: "The Dismemberment Plan", album: "Change", released: "2001", spotify: "" },
  { artist: "The Dismemberment Plan", album: "Emergency & I", released: "1999", spotify: "" },
  { artist: "The Flaming Lips", album: "Embryonic", released: "2009", spotify: "" },
  { artist: "The Flaming Lips", album: "The Soft Bulletin", released: "1999", spotify: "" },
  { artist: "The Flaming Lips", album: "Yoshimi Battles the Pink Robots", released: "2002", spotify: "" },
  { artist: "The Go-Betweens", album: "Liberty Belle and the Black Diamond Express", released: "1986", spotify: "" },
  { artist: "The Go! Team", album: "Thunder, Lightning, Strike", released: "2004", spotify: "" },
  { artist: "The Hold Steady", album: "Boys and Girls in America", released: "2006", spotify: "" },
  { artist: "The Hold Steady", album: "Separation Sunday", released: "2005", spotify: "" },
  { artist: "The House of Love", album: "The House of Love", released: "1990", spotify: "" },
  { artist: "The Jesus and Mary Chain", album: "Psychocandy", released: "1985", spotify: "https://open.spotify.com/album/0PnzJO3D4i85ALVJPaDpru" },
  { artist: "The Lemon Twigs", album: "Everything Harmony", released: "2023", spotify: "" },
  { artist: "The Libertines", album: "Up the Bracket", released: "2002", spotify: "" },
  { artist: "The Magnetic Fields", album: "69 Love Songs", released: "1999", spotify: "https://open.spotify.com/album/2GuROKcqyHdpIDcgxml1C7" },
  { artist: "The Microphones", album: "It Was Hot, We Stayed in the Water", released: "2000", spotify: "" },
  { artist: "The Microphones", album: "The Glow Pt. 2", released: "2001", spotify: "" },
  { artist: "The New Pornographers", album: "Electric Version", released: "2003", spotify: "" },
  { artist: "The New Pornographers", album: "Mass Romantic", released: "2000", spotify: "" },
  { artist: "The New Pornographers", album: "Twin Cinema", released: "2005", spotify: "" },
  { artist: "The Notwist", album: "Neon Golden", released: "2002", spotify: "" },
  { artist: "The Replacements", album: "All Shook Down", released: "1990", spotify: "" },
  { artist: "The Replacements", album: "Let It Be", released: "1984", spotify: "https://open.spotify.com/album/2sOLW5TSgXiLZBacdHxO6m" },
  { artist: "The Replacements", album: "Sorry Ma, Forgot to Take Out the Trash", released: "1981", spotify: "" },
  { artist: "The Shins", album: "Chutes Too Narrow", released: "2003", spotify: "" },
  { artist: "The Smiths", album: "Hatful of Hollow", released: "1984", spotify: "https://open.spotify.com/album/1j57Q5ntVi7crpibb0h4sv" },
  { artist: "The Smiths", album: "Strangeways, Here We Come", released: "1987", spotify: "https://open.spotify.com/album/7jfexk2w5aDI25njkN0UGg" },
  { artist: "The Smiths", album: "The Queen Is Dead", released: "1986", spotify: "https://open.spotify.com/album/5Y0p2XCgRRIjna91aQE8q7" },
  { artist: "The Stone Roses", album: "The Stone Roses", released: "1989", spotify: "https://open.spotify.com/album/0um9FI6BLBldL5POP4D4Cw" },
  { artist: "The Strokes", album: "Is This It", released: "2001", spotify: "https://open.spotify.com/album/2k8KgmDp9oHrmu0MIj4XDE", pick: true },
  { artist: "The Strokes", album: "Room on Fire", released: "2003", spotify: "https://open.spotify.com/album/3HFbH1loOUbqCyPsLuHLLh" },
  { artist: "The Triffids", album: "Born Sandy Devotional", released: "1986", spotify: "" },
  { artist: "The Unicorns", album: "Who Will Cut Our Hair When We're Gone?", released: "2003", spotify: "" },
  { artist: "The Verve", album: "A Northern Soul", released: "1995", spotify: "" },
  { artist: "The Verve", album: "Urban Hymns", released: "1997", spotify: "https://open.spotify.com/album/2okCg9scHue9GNELoB8U9g" },
  { artist: "The War on Drugs", album: "Lost in the Dream", released: "2014", spotify: "https://open.spotify.com/album/14xxjLlbGy8ACm4MorBjD5" },
  { artist: "The Waterboys", album: "This Is The Sea", released: "1985", spotify: "" },
  { artist: "The Weather Station", album: "Ignorance", released: "2021", spotify: "" },
  { artist: "The White Stripes", album: "Elephant", released: "2003", spotify: "https://open.spotify.com/album/6D9urpsOWWKtYvF6PaorGE" },
  { artist: "The White Stripes", album: "Icky Thump", released: "2007", spotify: "https://open.spotify.com/album/1Mu6HgmdfdiQTOZ8mPEyFU" },
  { artist: "The White Stripes", album: "White Blood Cells", released: "2001", spotify: "https://open.spotify.com/album/6Xvc1TfpVEhDeHhmTQEtp0" },
  { artist: "The Wildhearts", album: "Earth vs the Wildhearts", released: "1993", spotify: "" },
  { artist: "The xx", album: "xx", released: "2009", spotify: "https://open.spotify.com/album/2nXJkqkS1tIKIyhBcFMmwz" },
  { artist: "Tindersticks", album: "Tindersticks", released: "1993", spotify: "" },
  { artist: "Titus Andronicus", album: "The Monitor", released: "2010", spotify: "" },
  { artist: "TV on the Radio", album: "Dear Science", released: "2008", spotify: "" },
  { artist: "TV on the Radio", album: "Return to Cookie Mountain", released: "2006", spotify: "" },
  { artist: "Twisted Teens", album: "Florida Water Blues", released: "", spotify: "" },
  { artist: "U2", album: "Achtung Baby", released: "1991", spotify: "https://open.spotify.com/album/0ta5VdkJcpdVnNrn7g4cZe" },
  { artist: "U2", album: "All That You Can't Leave Behind", released: "2000", spotify: "https://open.spotify.com/album/7gskILm9UyDvFlmmAoqn2g" },
  { artist: "U2", album: "The Joshua Tree", released: "1987", spotify: "https://open.spotify.com/album/5vBZRYu2GLA65nfxBvG1a7" },
  { artist: "U2", album: "War", released: "1983", spotify: "https://open.spotify.com/album/6GaqU0TlYBKHUiSJ0AT9A2" },
  { artist: "U2", album: "Zooropa", released: "1993", spotify: "" },
  { artist: "Ultra Vivid Scene", album: "Joy 1967-1990", released: "1990", spotify: "" },
  { artist: "Unrest", album: "Imperial f.f.r.r.", released: "1992", spotify: "" },
  { artist: "Vampire Weekend", album: "Contra", released: "2010", spotify: "https://open.spotify.com/album/0zeAijecFGZOS4OaRdPVz5" },
  { artist: "Vampire Weekend", album: "Modern Vampires of the City", released: "2013", spotify: "https://open.spotify.com/album/1GXMNFfoHF4sN7lG8gZq1j" },
  { artist: "Vampire Weekend", album: "Only God Was Above Us", released: "2024", spotify: "" },
  { artist: "Vampire Weekend", album: "Vampire Weekend", released: "2008", spotify: "https://open.spotify.com/album/7n8NJkGKAl2np1bXiRn0CY" },
  { artist: "Wednesday", album: "Bleeds", released: "2025", spotify: "" },
  { artist: "Wednesday", album: "Rat Saw God", released: "2023", spotify: "" },
  { artist: "Weezer", album: "Pinkerton", released: "1996", spotify: "https://open.spotify.com/album/04vEXDRrNmiovdqYrfV0aH" },
  { artist: "Weezer", album: "Weezer (The Blue Album)", released: "1994", spotify: "" },
  { artist: "Wilco", album: "Being There", released: "1996", spotify: "" },
  { artist: "Wilco", album: "Summerteeth", released: "1999", spotify: "" },
  { artist: "Wilco", album: "Yankee Hotel Foxtrot", released: "2001", spotify: "https://open.spotify.com/album/0rPtXOMN42nsLDiShvGamv" },
  { artist: "Wolf Parade", album: "Apologies to the Queen Mary", released: "2005", spotify: "" },
  { artist: "Yeah Yeah Yeahs", album: "Fever to Tell", released: "2003", spotify: "https://open.spotify.com/album/0EabZMx74C2wyXhvMMO1eI" },
  { artist: "Yeah Yeah Yeahs", album: "It's Blitz!", released: "2009", spotify: "https://open.spotify.com/album/6w21zEx5okRPCYJejLVRdR" },
  { artist: "Yeule", album: "Softscars", released: "2023", spotify: "" },
  { artist: "Yo La Tengo", album: "And Then Nothing Turned Itself Inside-Out", released: "2000", spotify: "" },
  { artist: "Yo La Tengo", album: "I Can Hear the Heart Beating as One", released: "1997", spotify: "https://open.spotify.com/album/3V18DIKvRuwdxc2LE4wuac" },
  { artist: "You Am I", album: "Hi Fi Way", released: "1995", spotify: "" },

  { artist: "", album: "", released: "", spotify: "" },

]);
