/* Jazz
   ----
   One line per album. Copy the blank line, fill in the quotes, and keep
   the comma at the end. The blank line itself is ignored.

     artist    "Metallica"
     album     "Master of Puppets"
     released  "1986"  or  "1986-03-03"     (used by the release-date sorts)
     spotify   the album's Spotify link      (Play opens it, and its cover is used)

   Optional extras, added inside the { } with a comma before each:
     pick: true                    Staff Pick in this room
     note: "..."                   handwritten card under a Staff Pick
     type: "EP"                    small badge on the cover
     cover: "some-file.jpg"        use this image from images/covers/ instead (see below)
     link: "https://..."           Play opens this instead, for albums not on Spotify
     sortAs: "Dylan, Bob"          file it under a different name

   Covers come from Spotify by themselves. For an album that isn't on Spotify
   (or to use a different picture), save the image in images/covers/ named
   exactly  Artist - Album.jpg  (or .png), e.g.
   images/covers/Chuck Berry - Chuck Berry's Golden Decade.jpg
   Leave out characters Windows won't allow in file names ( \ / : * ? " < > | ).
   A cover: "..." on the line beats everything; a saved Artist - Album file is
   used when there's no Spotify cover; Melodic Mosaic's cover after that.
*/

shelf([

  { artist: "Ahmad Jamal", album: "At the Pershing: But Not for Me", released: "1958", spotify: "" },
  { artist: "Alice Coltrane", album: "Universal Consciousness", released: "1971", spotify: "" },
  { artist: "Andrew Hill", album: "Point of Departure", released: "1965", spotify: "" },
  { artist: "Archie Shepp", album: "Four for Trane", released: "1965", spotify: "" },
  { artist: "Art Blakey and the Jazz Messengers", album: "Moanin'", released: "1958", spotify: "" },
  { artist: "Art Blakey and The Jazz Messengers with Thelonious Monk", album: "Art Blakey's Jazz Messengers with Thelonious Monk", released: "1958", spotify: "" },
  { artist: "Art Pepper", album: "Art Pepper Meets the Rhythm Section", released: "1957", spotify: "" },
  { artist: "Art Tatum", album: "Piano Starts Here", released: "1968", spotify: "" },
  { artist: "BADBADNOTGOOD", album: "BBNG2", released: "2012", spotify: "" },
  { artist: "Benny Goodman", album: "Carnegie Hall Jazz Concert (The Famous 1938 Carnegie Hall Jazz Concert)", released: "1998", spotify: "" },
  { artist: "Benny Goodman and His Orchestra, Benny Goodman Trio, The Benny Goodman Quartet", album: "Jazz Concert No.2 1937-1938", released: "1950", spotify: "" },
  { artist: "The Bill Evans Trio", album: "Sunday at the Village Vanguard", released: "1961", spotify: "" },
  { artist: "The Bill Evans Trio", album: "Waltz for Debby", released: "1961", spotify: "" },
  { artist: "Billie Holiday", album: "Billie Holiday at Jazz at the Philharmonic", released: "1954", spotify: "" },
  { artist: "Billie Holiday", album: "Lady Day: The Best Of Billie Holiday", released: "2001", spotify: "" },
  { artist: "Billie Holiday", album: "Lady In Satin", released: "1958", spotify: "https://open.spotify.com/album/4LrLP7DM1KBj8r2Sc098JA" },
  { artist: "Billie Holiday", album: "The Complete Original American Decca Recordings", released: "1991", spotify: "" },
  { artist: "Billie Holiday", album: "The Legacy (1933-1958)", released: "1991", spotify: "" },
  { artist: "Bud Powell", album: "The Amazing Bud Powell: Volume 1", released: "1956", spotify: "" },
  { artist: "Bud Powell", album: "The Genius of Bud Powell", released: "1956", spotify: "" },
  { artist: "Cannonball Adderley", album: "Somethin' Else", released: "1958", spotify: "" },
  { artist: "Cecil Taylor", album: "Live at the Cafe Montmartre", released: "1963", spotify: "" },
  { artist: "Cecil Taylor", album: "Unit Structures", released: "1966", spotify: "" },
  { artist: "Charles Mingus", album: "Changes One", released: "1975", spotify: "" },
  { artist: "Charles Mingus", album: "Changes Two", released: "1975", spotify: "" },
  { artist: "Charles Mingus", album: "Mingus Ah Um", released: "1959", spotify: "https://open.spotify.com/album/4Z8nWz3dGybOP7lhMZpcOo" },
  { artist: "Charles Mingus", album: "The Black Saint and the Sinner Lady", released: "1963", spotify: "" },
  { artist: "Charlie Christian", album: "The Genius of the Electric Guitar", released: "1987", spotify: "" },
  { artist: "Charlie Christian", album: "Solo Flight: The Genius of Charlie Christian", released: "1972", spotify: "" },
  { artist: "Charlie Parker", album: "Bird / The Complete Original Master Takes. The Savoy Recordings", released: "1988", spotify: "" },
  { artist: "Charlie Parker", album: "Charlie Parker with Strings", released: "1955", spotify: "" },
  { artist: "Charlie Parker", album: "The Complete Savoy and Dial Studio Recordings 1944-1948", released: "2000", spotify: "" },
  { artist: "Chet Baker", album: "(Chet Baker Sings) It Could Happen to You", released: "1958", spotify: "" },
  { artist: "Chet Baker", album: "The Best of Chet Baker Sings", released: "1989", spotify: "" },
  { artist: "Chick Corea", album: "Now He Sings, Now He Sobs", released: "1968", spotify: "" },
  { artist: "Chick Corea", album: "Return to Forever", released: "1972", spotify: "" },
  { artist: "Clifford Brown and Max Roach", album: "Study in Brown", released: "1955", spotify: "" },
  { artist: "Clifford Brown, Max Roach", album: "Clifford Brown and Max Roach at Basin Street", released: "1956", spotify: "" },
  { artist: "Coleman Hawkins", album: "Body and Soul", released: "1996", spotify: "" },
  { artist: "Count Basie", album: "The Complete Atomic Basie", released: "1994", spotify: "" },
  { artist: "Count Basie and His Orchestra", album: "The Atomic Mr. Basie", released: "1958", spotify: "" },
  { artist: "Count Basie and His Orchestra", album: "The Complete Decca Recordings", released: "1992", spotify: "" },
  { artist: "Dexter Gordon", album: "Go!", released: "1962", spotify: "" },
  { artist: "Dizzy Gillespie", album: "Afro", released: "1954", spotify: "" },
  { artist: "Dizzy Gillespie", album: "The Complete RCA Victor Recordings", released: "1995", spotify: "" },
  { artist: "Dizzy Gillespie and His Sextets and Orchestra", album: "Shaw ’Nuff", released: "1992", spotify: "" },
  { artist: "Duke Ellington", album: "Ellington at Newport (Complete)", released: "1999", spotify: "" },
  { artist: "Duke Ellington", album: "Ellington at Newport (Original)", released: "1956", spotify: "" },
  { artist: "Duke Ellington", album: "The Blanton-Webster Band", released: "1990", spotify: "" },
  { artist: "Ella Fitzgerald", album: "Ella Fitzgerald Sings the Cole Porter Song Book", released: "1956", spotify: "" },
  { artist: "Ella Fitzgerald", album: "Ella Fitzgerald Sings the Duke Ellington Song Book", released: "1957", spotify: "" },
  { artist: "Ella Fitzgerald", album: "Ella in Berlin: Mack the Knife", released: "1960", spotify: "" },
  { artist: "Ella Fitzgerald and Louis Armstrong", album: "Ella and Louis", released: "1956", spotify: "" },
  { artist: "Eric Dolphy", album: "Out to Lunch!", released: "1964", spotify: "" },
  { artist: "Floating Points, Pharoah Sanders and the London Symphony Orchestra", album: "Promises", released: "2021", spotify: "" },
  { artist: "Frank Sinatra", album: "Sinatra at the Sands", released: "1966", spotify: "" },
  { artist: "Frank Sinatra", album: "Songs for Swingin' Lovers!", released: "1956", spotify: "https://open.spotify.com/album/4kca7vXd1Wo5GE2DMafvMc" },
  { artist: "George Russell", album: "New York, N.Y.", released: "1959", spotify: "" },
  { artist: "George Russell", album: "The Jazz Workshop", released: "1957", spotify: "" },
  { artist: "Gerry Mulligan Quartet", album: "The Original Quartet With Chet Baker", released: "1998", spotify: "" },
  { artist: "Grant Green", album: "Idle Moments", released: "1965", spotify: "" },
  { artist: "Hank Mobley", album: "Soul Station", released: "1960", spotify: "" },
  { artist: "Herbie Hancock", album: "Head Hunters", released: "1973", spotify: "https://open.spotify.com/album/5fmIolILp5NAtNYiRPjhzA" },
  { artist: "Herbie Hancock", album: "Maiden Voyage", released: "1965", spotify: "" },
  { artist: "Jaco Pastorius", album: "Jaco Pastorius", released: "1976", spotify: "" },
  { artist: "Jelly Roll Morton", album: "The Centennial - His Complete Victor Recordings", released: "1990", spotify: "" },
  { artist: "Jelly Roll Morton", album: "Volume 1", released: "1989", spotify: "" },
  { artist: "Jimmy Smith", album: "The Sermon!", released: "1959", spotify: "" },
  { artist: "Jimmy Smith at the Organ", album: "A New Sound... A New Star..., Vol. 1", released: "1956", spotify: "" },
  { artist: "Joe Henderson", album: "Inner Urge", released: "1966", spotify: "" },
  { artist: "John Coltrane", album: "A Love Supreme", released: "1965", spotify: "https://open.spotify.com/album/7Eoz7hJvaX1eFkbpQxC5PA" },
  { artist: "John Coltrane", album: "Blue Train", released: "1958", spotify: "" },
  { artist: "John Coltrane", album: "Giant Steps", released: "1960", spotify: "https://open.spotify.com/album/6NkgPYCMAzttRIKDpuJrFp" },
  { artist: "John Coltrane", album: "Impressions", released: "1963", spotify: "" },
  { artist: "John Coltrane", album: "My Favorite Things", released: "1961", spotify: "" },
  { artist: "John Coltrane", album: "The Complete 1961 Village Vanguard Recordings", released: "1997", spotify: "" },
  { artist: "John Coltrane and Johnny Hartman", album: "John Coltrane and Johnny Hartman", released: "1963", spotify: "" },
  { artist: "John McLaughlin", album: "Extrapolation", released: "1969", spotify: "" },
  { artist: "Kamasi Washington", album: "The Epic", released: "2015", spotify: "" },
  { artist: "Keith Jarrett", album: "The Köln Concert", released: "1975", spotify: "" },
  { artist: "Kenny Burrell", album: "Midnight Blue", released: "1963", spotify: "" },
  { artist: "Kenyon Hopkins", album: "Nightmare!!", released: "1962", spotify: "" },
  { artist: "Krzysztof Komeda", album: "Astigmatic", released: "1966", spotify: "" },
  { artist: "Krzysztof Komeda", album: "Rosemary's Baby", released: "2012", spotify: "" },
  { artist: "Krzysztof Komeda", album: "Rosemary's Baby", released: "2014", spotify: "" },
  { artist: "Kurt Rosenwinkel", album: "The Next Step", released: "2001", spotify: "" },
  { artist: "Lee Konitz", album: "Motion", released: "1961", spotify: "" },
  { artist: "Lee Morgan", album: "The Sidewinder", released: "1964", spotify: "" },
  { artist: "Lennie Tristano", album: "Lennie Tristano", released: "1956", spotify: "" },
  { artist: "Lester Young", album: "The Complete Aladdin Recordings Of Lester Young", released: "1995", spotify: "" },
  { artist: "Louis Armstrong", album: "Hot Fives & Sevens", released: "1999", spotify: "" },
  { artist: "Louis Armstrong", album: "Satchmo at Symphony Hall", released: "1951", spotify: "" },
  { artist: "Louis Armstrong", album: "The Complete Hot Five & Hot Seven Recordings", released: "2003", spotify: "" },
  { artist: "Mahavishnu Orchestra", album: "The Inner Mounting Flame", released: "1971", spotify: "" },
  { artist: "Matana Roberts", album: "Coin Coin Chapter Four: Memphis", released: "2019", spotify: "" },
  { artist: "McCoy Tyner", album: "The Real McCoy", released: "1967", spotify: "" },
  { artist: "Michael Brecker", album: "Tales from the Hudson", released: "1996", spotify: "" },
  { artist: "Miles Davis", album: "Birth of the Cool", released: "1957", spotify: "" },
  { artist: "Miles Davis", album: "Bitches Brew", released: "1970", spotify: "https://open.spotify.com/album/3Q0zkOZEOC855ErOOJ1AdO" },
  { artist: "Miles Davis", album: "Filles de Kilimanjaro", released: "1969", spotify: "" },
  { artist: "Miles Davis", album: "In A Silent Way", released: "1969", spotify: "" },
  { artist: "Miles Davis", album: "Kind of Blue", released: "1959", spotify: "https://open.spotify.com/album/1weenld61qoidwYuZ1GESA" },
  { artist: "Miles Davis", album: "Miles Ahead", released: "1957", spotify: "" },
  { artist: "Miles Davis", album: "Sketches of Spain", released: "1960", spotify: "https://open.spotify.com/album/2xyhltm9XWSQ5xok4C81BD" },
  { artist: "Miles Davis", album: "The Complete Live at the Plugged Nickel 1965", released: "1995", spotify: "" },
  { artist: "Modern Jazz Quartet", album: "Fontessa", released: "1956", spotify: "" },
  { artist: "Nala Sinephro", album: "Endlessness", released: "2024", spotify: "" },
  { artist: "Nina Simone", album: "Nina Simone in Concert", released: "1964", spotify: "" },
  { artist: "Nina Simone", album: "Nina Simone Sings the Blues", released: "1967", spotify: "" },
  { artist: "Nina Simone", album: "Pastel Blues", released: "1965", spotify: "" },
  { artist: "Nina Simone", album: "Wild Is the Wind", released: "1966", spotify: "https://open.spotify.com/album/2EYVXfypcucR62WMKJl6Mr" },
  { artist: "Oliver Nelson", album: "The Blues and the Abstract Truth", released: "1961", spotify: "" },
  { artist: "Ornette Coleman", album: "Free Jazz: A Collective Improvisation", released: "1961", spotify: "" },
  { artist: "Ornette Coleman", album: "The Shape of Jazz to Come", released: "1959", spotify: "https://open.spotify.com/album/2iPH3iUmpa9ufIpwY76keF" },
  { artist: "Pat Metheny", album: "80/81", released: "1980", spotify: "" },
  { artist: "Pat Metheny", album: "Bright Size Life", released: "1976", spotify: "" },
  { artist: "Pharoah Sanders", album: "Karma", released: "1969", spotify: "" },
  { artist: "Portico Quartet", album: "Portico Quartet", released: "2012", spotify: "" },
  { artist: "Rahsaan Roland Kirk", album: "Rip, Rig and Panic", released: "1965", spotify: "" },
  { artist: "Sonny Rollins", album: "A Night at the \"Village Vanguard\"", released: "1958", spotify: "" },
  { artist: "Sonny Rollins", album: "Saxophone Colossus", released: "1957", spotify: "" },
  { artist: "Sonny Rollins", album: "The Bridge", released: "1962", spotify: "" },
  { artist: "Sons of Kemet", album: "Your Queen Is a Reptile", released: "2018", spotify: "" },
  { artist: "Stan Getz", album: "Focus", released: "1962", spotify: "" },
  { artist: "Stan Getz", album: "West Coast Jazz", released: "1955", spotify: "" },
  { artist: "Stan Getz and João Gilberto", album: "Getz/Gilberto", released: "1964", spotify: "https://open.spotify.com/album/73ZRKdD3Ds43IjHrhKgucY" },
  { artist: "Sun Ra", album: "The Heliocentric Worlds of Sun Ra, Volume One", released: "1965", spotify: "" },
  { artist: "Sun Ra", album: "The Magic City", released: "1966", spotify: "" },
  { artist: "The Albert Ayler Trio", album: "Spiritual Unity", released: "1965", spotify: "" },
  { artist: "The Dave Brubeck Quartet", album: "Time Out", released: "1959", spotify: "" },
  { artist: "The Horace Silver Quintet", album: "Song for My Father", released: "1964", spotify: "" },
  { artist: "The Horace Silver Quintet & Trio", album: "Blowin' the Blues Away", released: "1959", spotify: "" },
  { artist: "The Jan Garbarek Quartet", album: "Afric Pepperbird", released: "1971", spotify: "" },
  { artist: "The Oscar Peterson Trio", album: "Night Train", released: "1963", spotify: "" },
  { artist: "The Peter Brötzmann Octet", album: "Machine Gun", released: "1968", spotify: "" },
  { artist: "The Quintet", album: "Jazz at Massey Hall", released: "1953", spotify: "" },
  { artist: "The Stan Tracey Quartet", album: "Jazz Suite Inspired by Dylan Thomas's \"Under Milk Wood\"", released: "1965", spotify: "" },
  { artist: "The Tony Williams Lifetime", album: "Emergency!", released: "1969", spotify: "" },
  { artist: "The Wynton Kelly Trio and Wes Montgomery", album: "Smokin’ at the Half Note", released: "1965", spotify: "" },
  { artist: "Thelonious Monk", album: "Brilliant Corners", released: "1957", spotify: "" },
  { artist: "Thelonious Monk", album: "Genius of Modern Music: Volume 1", released: "1956", spotify: "" },
  { artist: "Thelonious Monk", album: "The Complete Blue Note Recordings", released: "1994", spotify: "" },
  { artist: "Thelonious Monk Quartet with John Coltrane", album: "At Carnegie Hall", released: "2005", spotify: "" },
  { artist: "Wayne Shorter", album: "Speak No Evil", released: "1966", spotify: "" },
  { artist: "Weather Report", album: "Heavy Weather", released: "1977", spotify: "" },
  { artist: "Weather Report", album: "I Sing the Body Electric", released: "1972", spotify: "" },
  { artist: "Weather Report", album: "Mysterious Traveller", released: "1974", spotify: "" },
  { artist: "Wes Montgomery", album: "Incredible Jazz Guitar", released: "1960", spotify: "" },
  { artist: "Wes Montgomery", album: "The Incredible Jazz Guitar of Wes Montgomery", released: "1960", spotify: "" },
  { artist: "Woody Herman", album: "The Thundering Herds", released: "1966", spotify: "" },

  { artist: "", album: "", released: "", spotify: "" },

]);
